### ISSUE TITLE
Connection problem caused by annyang

### ISSUE THREAD

**Issue by JVRibeiro** [TalAter/annyang#106]
<i>I am Brazilian and my English is terrible. Ignore it.</i>

I've been having problems with the use of Annyang on some computers. By allowing the microphone use, the internet connection is interrupted. In any site I try to open in any browser (of some computers) appears to connection failure screen.

After that, the internet does not work for a while (about 1 minute) and back to normal, if the application in which I use annyang is closed or if I remove the microphone permission.

Any suggestions of what might be happening?

**Comment by TalAter** [comment]
I can't really think of how or why this might happen. I suggest reporting a bug with SpeechRecognition with Google's Chrome team.
