### ISSUE TITLE
Annyang is not running the command line.

### ISSUE THREAD

**Issue by Frostcraft** [TalAter/annyang#107]
I tried to get annyang to search Google on click of a button here is the code:
```html
<script src="//cdnjs.cloudflare.com/ajax/libs/annyang/1.6.0/annyang.min.js"></script>
<script>
if (annyang) {
  var commands = {
    'search *term': function(term) {
      window.location.href = 'https://www.google.com/#q=site:frostcraft.netne.net'+term;
    }
  };
  annyang.addCommands(commands);
}
}
```
I then have a a button that when clicked, activates annyang.
The code is:
```html
<i class="mdi-av-mic" onclick="annyang.start();"></i>
```
Clicking on the button activates voice listening but it does not search for what I say on Google.

**Comment by TalAter** [comment]
@Frostcraft - I tried your code and it worked after I fixed some basic javascript errors like, an extra closing bracket, and missing `</script>`
If you could show me the complete code, and explain exactly what happens, it will be easier for me to help you.
