### ISSUE TITLE
Use comands with multiple optional words

### ISSUE THREAD

**Issue by JVRibeiro** [TalAter/annyang#108]
It would be good if we could use optional words in one command. One example is when we want to use more than one phrase for the same function:

```javascript
if (annyang) {
commands = {
  'open my (notes|reminders)': function () { /* content */ }
 }
}
```

In that case will be recognized both "notes" and "reminders" as the same thing. Is it possible?

**Comment by ArkeologeN** [comment]
I believe, the match pattern shouldn't be the object key. So that, the pattern could always be a string or a regex. I think the author should move the command critria from key/value pair to value/sibling pairs. I didn't found a way to do something like:

```
{

   /^what time is it/i: function() { ... }
}
```

Not sure, if I putting regex string in "quotes" could work either.

**Comment by TalAter** [comment]
Version 2.0.0 released yesterday adds support for regular expressions in commands, so you can now do something like this:

````javascript
var commands = {
  'hello :name': {'regexp': /^(?:hello|howdy|hi) (\w*)$/, 'callback': greetFunction}
}
````

@ArkeologeN  I used a similar API to the one you suggest here. I would appreciate your feedback.

You can read the full release notes on this and other new features here: https://github.com/TalAter/annyang/releases/tag/v2.0.0

**Comment by ArkeologeN** [comment]
@TalAter thanks for the update! I am gonna implement that and come back to you with feedback.

One more question, I suppose the recognition would working from dictionary, right? Would there be any possibility to teach the probability table to recognizer? What if I know the input would be from within the set of words (or bagOfWords)?

Something like this, may be? http://syl22-00.github.io/pocketsphinx.js/
