### ISSUE TITLE
It does not work in IE and Firefox

### ISSUE THREAD

**Issue by Mahesh-Virupa** [TalAter/annyang#109]
HI, 

This library does not support  IE and Firefox. All of our customer uses this browsers.
Are there any plans to support this in future and by what timeline ?

Thanks,
Mahesh

**Comment by JVRibeiro** [comment]
For now just Google Chrome supports voice commands, this has nothing to do with Annyang. We hope that more modern browsers add support for speech recognition.

**Comment by TalAter** [comment]
As @JVRibeiro said... annyang works according to the W3C's SpeechRecognition spec, and it is up to the browsers to implement the API.

I encourage you to take this question to Mozilla and Microsoft... :) I'd love to hear what they say
