### ISSUE TITLE
Can I use Annyang for commercial purposes?

### ISSUE THREAD

**Issue by JVRibeiro** [TalAter/annyang#110]
I'm building a Siri-like application for home automation. All commands were defined in the script annyang. What is my limitation on a commercial use?

**Comment by TalAter** [comment]
annyang is licensed under the MIT license, which means there aren't any real restrictions.
You can see it here: https://github.com/TalAter/annyang/blob/master/LICENSE

I would appreciate it if you added attribution to annyang's contribution to the project in the site/docs/etc.

And I would love to see whatever you build in action. Can you tell me more about the project?

**Comment by JVRibeiro** [comment]
I proudly put a great reference to Annyang and you, Tal Ater. Without this library my work would be impossible, it fits perfectly with my code. Of course, you will be able to see a demonstration of my work. I only ask that you wait a little bit, all the promotional material is being made and I'll let you know as soon as possible. Is there any way that I can warn you, email or something?

The original text (in case you prefer to translate by yourself):
Orgulhosamente eu colocarei uma grande referência ao Annyang e a você, Tal Ater. Sem essa biblioteca meu trabalho seria impossível, ela se encaixa perfeitamente aos meus códigos. E claro, você vai poder ver uma demonstração do meu trabalho. Apenas peço que aguarde um pouquinho, todo o material de divulgação está sendo feito e eu avisarei assim que puder. Há algum meio em que eu possa te avisar, email ou algo assim?
