### ISSUE TITLE
resume annyang with voice

### ISSUE THREAD

**Issue by wizardsambolton** [TalAter/annyang#111]
Hi say i wanted to pause annyang (with annyang.pause()) would it be possible to to resume with a voice command?
@TalAter

**Comment by rmilesson** [comment]
No. Doesn't seem possible to do with annyang.

For further info check [here](https://github.com/TalAter/annyang/blob/ba1e79eb65754611e61ebed20e0733b3166d3d1b/annyang.js#L167).

**Comment by JVRibeiro** [comment]
What you can do: Add two commands objects (commands and commands2). In the commands2 you put 

'resume': function() {
annyang.pause();
annyang.removeCommans();
annyang.addComand(commands);
annyang.resume();
}



In commands object, you can use this function:

'pause': function() {
annyang.pause();
annyang.removeCommans();
annyang.addComand(commands2);
annyang.resume();
}

I hope it helps you. Sorry for my English.

**Comment by wizardsambolton** [comment]
@JVRibeiro Hi! it is now telling me that annyang.pause() is not  function

**Comment by JVRibeiro** [comment]
Oops. I didn't noticed before my mistakes. Use this: 

'resume': function() {
 annyang.pause();
 annyang.removeCommands();
 annyang.addCommand(commands);
 annyang.resume();
 }

And:

'pause': function() {
 annyang.pause();
 annyang.removeCommands();
 annyang.addCommand(commands2);
 annyang.resume();
 }

**Comment by wizardsambolton** [comment]
@JVRibeiro nope aparently annyang.pause() is still not a function

**Comment by JVRibeiro** [comment]
Try annyang.stop() instead.

**Comment by wizardsambolton** [comment]
suprise suprise annyang.stop() is not a function

**Comment by wizardsambolton** [comment]
@JVRibeiro ok fixed that problem now addcommand is not a function

**Comment by wizardsambolton** [comment]
@JVRibeiro ok everything is workiing fine now exept the: nnyang. addCallback('resultNoMatch',) still runs, any ideas?

**Comment by TalAter** [comment]
@JVRibeiro That's a great idea. I think you can even do without pausing/stopping and resuming/starting.

Simply:
````
annyang.removeCommands();
annyang.addCommands(commands2);
````
and vice-versa
