### ISSUE TITLE
Different word for same function

### ISSUE THREAD

**Issue by GuiCarneiro** [TalAter/annyang#113]
Does annyang have support for different words to a same result?

Something like :
"[ Hello | Hi | Howdy ] James" : helloFunction

**Comment by wizardsambolton** [comment]
yes it is '(hello)(hi)(howdy) James' : helloFunction. hope this helps!

**Comment by JVRibeiro** [comment]
@wizardsambolton The only problem with this code is: If we say "James" only, it will be also recognized as a hello function. I don't know if we can use regex.

**Comment by wizardsambolton** [comment]
ok then maybe '(hello james)(hi james)(howdy james)' : hellofunction

**Comment by JVRibeiro** [comment]
Sam, noticed you're constructing a Jarvis system in JavaScript. Me too. Here is not the right place to talk about it. Let's talk?

**Comment by wizardsambolton** [comment]
@JVRibeiro ok sure! my email is on my profile

**Comment by TalAter** [comment]
Version 2.0.0 released yesterday adds support for regular expressions in commands, so you can now do something like this:

````javascript
var commands = {
  'hello :name': {'regexp': /^(?:hello|howdy|hi) (\w*)$/, 'callback': greetFunction}
}
````

You can read the full release notes on this and other new features here: https://github.com/TalAter/annyang/releases/tag/v2.0.0

@JVRibeiro , @wizardsambolton - I would love your feedback on the release.
