### ISSUE TITLE
Adding commands without hardcoding them

### ISSUE THREAD

**Issue by Maikell84** [TalAter/annyang#114]
Hello there!

I have a question regarding the commands-object.
This works fine:

        var commands = {
            'goodbye': function() {  closeApp(); },
            'help': function() { displayHelp(); }
            //and so on...
        };
        annyang.addCommands(commands);

But this object literal notation leads to the problem, that I am not able to add a command, which is "variable". Because I want to load a set of user defined commands out of a database or a textfile.

Is there a way to achieve this? Can I add voicecommands without hard-coding them?

Best regards
Michael

**Comment by vedraan** [comment]
@Maikell84 does this not work:
```
var customCommand = 'bye';
var commands = {
        'goodbye': function() {  closeApp(); },
        'help': function() { displayHelp(); }
        //and so on...
    };
commands[customCommand] = function() { quit(); };
```

**Comment by Maikell84** [comment]
Hello.
Thank You very much - This works perfectly.
