### ISSUE TITLE
How to specify multiple languages

### ISSUE THREAD

**Issue by poshetz** [TalAter/annyang#119]
How do i specify multiple languages codes to listen for?

Will this get both languages or only the last one i set?

```
annyang.setLanguage('en-EN');
annyang.setLanguage('en-US');
```

Thank you a lot

**Comment by TalAter** [comment]
Only the last language set when the user starts speaking will be used... That's just the way the SpeechRecognition engine works, nothing annyang can control.

**Comment by poshetz** [comment]
crazy but ok, thank you for the awesome lib!

**Comment by poshetz** [comment]
@TalAter sorry for disturbing again, i was just wondering, which is the best practice to translate commands into 4/5 languages, should i duplicate them all for each lang?

**Comment by TalAter** [comment]
If I understand correctly, you'd like to define all the commands in advance and switch languages?

But I think it might be better to remove all commands, and register new ones every time you switch languages... This could prevent clashes between words that sound the same in different languages.

````javascript
// this won't work!
var commands = {
  'hi': function() { alert('Hello!'); },
  'hi': function() { alert('Ola!'); },
  'hi': function() { alert('Hola!'); }
};
````

**Comment by poshetz** [comment]
@TalAter Hi thank you , what i meant was:
```var commands = {
  'hello': function() { do() },
  'hola': function() { do() },
  'bonjour': function() { do()}
};
```
doing like this i'll have to duplicate do() for every translation !?
Thank you!

**Comment by TalAter** [comment]
Or you could define the function once, and then pass it by reference or name:

````javascript
var myDo = function() {
  do();
};
var commands = {
  'hello': myDo,
  'hola': myDo,
  'bonjour': myDo
};
````

**Comment by poshetz** [comment]
@TalAter  Yes, i will try something like that, thank you a lot for your support!
