### ISSUE TITLE
Numeric words?

### ISSUE THREAD

**Issue by poshetz** [TalAter/annyang#121]
Is there any way to detect words like twenty or ten as numeric words?
command example:
```'today date is *date': function (date) { 
console.log('date');
}```
I mean, if for example i want to  say a date  "four july" it will be not "4 july" , how can i manage/handle this?

thank you!!!

**Comment by TalAter** [comment]
There isn't something specifically for that. Can you explain a bit more about what you have in mind, your problem, and maybe some examples?

**Comment by poshetz** [comment]
Hi, was just that sometimes speech recognition returns "one" or "1" when you say ONE :D

So i was trying to udnerstand which criteria it uses

**Comment by TalAter** [comment]
Google works in mysterious ways. It will be safest to try and capture both.

**Comment by poshetz** [comment]
@TalAter  i think yes, i found many libraries and scripts to anyway convert numbers words to int and int to words so i think it's the only way, thank you for your support ! :+1:
