### ISSUE TITLE
add a option for callback for list of recognised words in the API

### ISSUE THREAD

**Issue by sktguha** [TalAter/annyang#122]
I suggest adding an option in the api for the function to recieve the list of recoginsed phrases so that one can write custom logic with it

**Comment by TalAter** [comment]
Hi @sktguha 
Just so I can understand better, can you give an example of what the function will receive and how you would use it?

**Comment by sktguha** [comment]
yes actually looking at it a second time it looks a bit complicated
perhaps it is possible to register an callback function to annyang as 
[code]
annyang.addEventListener('recognised', function(arr, listOfCommands){
   //so arr contains the list of recognised phrases by the speech recognisation engine
   // listOfCommands contain the list of commands added upto now to annyang
  
});
[/code]

**Comment by TalAter** [comment]
Can you give an example of how you would use this and what for?

**Comment by sktguha** [comment]
well for example if I want to use a <b>custom logic</b> for triggering the actions. for example if I want to trigger the action even if the user has spoken, say the original phrase was "the expressway is to the left" but the user has spoken "the highway is to the left".
Also sometimes the user speaks the entire phrase correctly but it is recognised as seperate parts
for example "Hello how are you" is interpreted as "Hello how" and "are you"
I believe it can be done currently by turning debug mode on and overriding console.log function  but I guess that isn't the best way. 

Also on that note I wonder if it possible to provide such a callback function so that say the application can display to the user the currently recognised phrases. Infact I needed to do this for my current application. for now I override the console.log function so that I could diplay to the user the phrases currently recognised by the engine so that the user does not become frustrated.

**Comment by sktguha** [comment]
Hi,
Any updates ?

**Comment by TalAter** [comment]
I just release v2.0.0 last night, inspired by your ideas.

One of the  features added, is that callbacks you register may now return with a list of recognized phrases.
For example:
````javascript
annyang.addCallback('resultNoMatch', function(phrases) {
  console.log('No command matched. Possible sentences said:');
  console.log(phrases);
});

annyang.addCallback('result', function(phrases) {
  console.log('Speech recognized. Possible sentences said:');
  console.log(phrases);
});

annyang.addCallback('resultMatch', function(said, commandMatched, phrases) {
  console.log('Command matched');
  console.log('The phrase the user said that matched a command');
  console.log(said);
  console.log('The command that was matched');
  console.log(commandMatched);
  console.log('An array of possible alternative phrases the user might\'ve said');
  console.log(phrases);
});
````

Version 2.0.0 also added support for regular expressions in the commands, so you can do something like this:
````javascript
var commands = {
  'the :road is to the :direction': {'regexp': /^the (?:highway|expressway) is to the (right|left)$/, 'callback': driveFunction}
}
````

You can read the full release notes here: https://github.com/TalAter/annyang/releases/tag/v2.0.0

**Comment by sktguha** [comment]
Hi,
Wow that is really great . Indeed the callback system seems superb. Thanks you very much for this.
Indeed anyang as a library is pretty good. I was able to start very fast with the demos on the homepage. I will try to contribute to the project if I get the time

**Comment by TalAter** [comment]
Thanks. :+1:
I would love to see what you build.

**Comment by sktguha** [comment]
Oh sure. 
https://github.com/sktguha/speechrecog
It is actually a simple demo of speech recognition based on iron man's video
The user has to speak the required words in place of iron man. They are shown instructions as speak "jarvis you there".
The video pauses at the points where iron man speaks, and on user speaking the required phrase, (in place of iron man) the video skips to the part where jarvis responds.
As of now there is a small bug. So if I seek to the point in the video, the video restarts intead of playing from the specified position( using vid.currentTime = POS). So I am thinking of using youtube API instead.

Also regarding unit testing annyang, issue https://github.com/TalAter/annyang/issues/91 ,  I suggest you to take a look at sinonJs (www.sinonjs.org). I have used it only for few toy examples but I think it is worth checking out

**Comment by TalAter** [comment]
Very cool idea! Would love to see it again when the restart issue is fixed.

As for Sinon... Yes, I've looked at that for https://github.com/TalAter/Carmen but I ended up using something called Georilla (which is the equivalant of what's needed for testing annyang, only for Geolocation testing). When I'm able to pursue writing tests for annyang, I'll look into that and Sinon again.
