### ISSUE TITLE
Doesn't work in Opera

### ISSUE THREAD

**Issue by NetOperatorWibby** [TalAter/annyang#124]
Before anyone says "this project only works in Chrome", I know this. However, these days, Opera is more like a clone of Chrome, with Opera flavoring on top. I can install Chrome Extensions (and use them!) in Opera.

I also do all my web development in Opera, before moving on to other browsers for fixes, if necessary. I just want to know if I can get annyang to work, it seems like a really great tool for a project I have.

**Comment by TalAter** [comment]
annyang is "Opera ready" :)

Unfortunately Opera still doesn't support the Web Speech API Specification. Hopefully this will change soon, as other browsers are slowly catching up. It looks like there's a lot of work by the Firefox team to add this soon, and hopefully Opera will follow.

To summarize, annyang is written to the Web Speech API Spec, and any browser that implements it will work with annyang. annyang even has specific provisions for opera prefixes (https://github.com/TalAter/annyang/blob/master/annyang.js#L28) ... the ball is in their court.

**Comment by NetOperatorWibby** [comment]
Smh, terrible. Thanks for the info!

**Comment by AdamMiltonBarker** [comment]
Why does the website say:

"annyang plays nicely with all browsers, progressively enhancing browsers that support SpeechRecognition, while leaving users with older browsers unaffected.""

When it doesn't ?

**Comment by TalAter** [comment]
Can you explain why you say it doesn't?
