### ISSUE TITLE
addCallback resultNotMatch won't work

### ISSUE THREAD

**Issue by poshetz** [TalAter/annyang#125]
Hi i simply added this code to your working example (exactly here https://github.com/TalAter/annyang/blob/master/demo/index.html#L93):
```
annyang.addCallback('resultNoMatch', function (e) {
console.log(e);
});
```

The problem is everything works fine but that event is never fired and nothing in console.

Debugging looks like only 'result' callback is returned but not the 'resultNoMatch' 

What this could be?

Thanks!!

**Comment by TalAter** [comment]
I just tried it, and it works: https://codepen.io/anon/pen/ZGPjjr?editors=100

Just say a phrase that isn't registered (like "woodchucks are awesome"), and the resultNoMatch callback will be triggered.

**Comment by poshetz** [comment]
Hey thank you i was using an old version of annyang :/ sorry for that!
