### ISSUE TITLE
Send text to annyang.

### ISSUE THREAD

**Issue by Sven65** [TalAter/annyang#126]
Hi, I think annyang is an amazing tool for voice recognision and I'm growing fonder of it every day.
Altough, I'd like to see a way to send text to it and have it be recognized by the engine and parsed via the commands object.

For example,

```javascript
annyang.sendText("text");
```

would parse the command "text"

Thanks

\- Mackan

**Comment by TalAter** [comment]
Thanks @Sven65 

Could you explain the use case for this? What are you trying to do? Could you not simply call the function that is mapped to that command?

**Comment by Sven65** [comment]
I can, altough, I'd like the simplicity of the commands object that is in annyang as this would make my application more user-friendly.

**Comment by TalAter** [comment]
@Sven65 I prefer to only put things in the library that will be beneficial for the majority of users, so that we can keep it light, and easy to maintain in the long run.

What would be a generic use case for this that could benefit many people?

**Comment by Sven65** [comment]
It would be useful among browsers that doesn't have voice support and make the library more universal.

**Comment by TalAter** [comment]
In browsers that don't have Speech Recognition support annyang doesn't load at all. This was done intentionally, so as to have the minimal impact on users that can't benefit from it (see https://github.com/TalAter/annyang/blob/master/annyang.js#L32).

So even if we add a `sendText` method, it won't be available to users in unsupported browsers.

It sounds like you might benefit from just using a router to handle this. You can look at annyang's "router" (https://github.com/TalAter/annyang/blob/master/annyang.js#L46) or more fully featured solutions.

**Comment by Sven65** [comment]
Oh, Okay, I'll have a look at the router, Thanks.

**Comment by rmilesson** [comment]
It would also be useful for testing purposes, wouldn't it?

**Comment by TalAter** [comment]
@rmilesson - Definitely. That is the use case I had in mind, and how I planned to implement testing of annyang... I did something similar with (the unreleased) carmen library (https://github.com/TalAter/Carmen/tree/master/test), using georilla to fake the geolocation object, and manually setting the user's location.

Having said that... implementing unit or functional tests for annyang is still some time away.

**Comment by rmilesson** [comment]
I could probably have a go at implementing something on Sunday unless I'm too hungover.

**Comment by TalAter** [comment]
Hungover?

Mental note: Check pull request 7 times :beers:
