### ISSUE TITLE
What is the best / suggested method to input more than 1 parameter (*val)?

### ISSUE THREAD

**Issue by chintanp** [TalAter/annyang#127]
Annyang command uses a *val to input values to the callback function. What should I do if I want to input more than one item ?

For example, I want to update a form based on user input. So I could have a command like 

    set Name *val

then val would contain the Name value that I could then assign to the field. But if my form has lot of fields writing a command like this for all fields could be tedious. Instead, I could have
    
    set *FieldName *FieldVal

This command, would return two parameters instead FieldName and FieldVal. If FieldName is valid name of available fields on the page, then I could update the value with FieldVal, or ignore the command. 

One way to achieve this, is, ofcourse parse the val to first get the FieldName and then FieldVal from a command like 

    set *val

but I dont think it would always result in clean solutions. 

is there a suggested method to achieve this ?

**Comment by TalAter** [comment]
Regular Expressions to the rescue: https://github.com/TalAter/annyang/tree/master/docs#using-regular-expressions-in-commands

**Comment by chintanp** [comment]
http://stackoverflow.com/questions/32440426/what-is-the-best-suggested-method-to-input-more-than-1-parameter-val-throug/32449660#32449660

Named-variables, is what I was looking for, thanks anyway. :)

**Comment by TalAter** [comment]
Yes. If your parameters are single words, that would be easiest. I guess I misunderstood your case. :+1:
