### ISSUE TITLE
issue in using regex example

### ISSUE THREAD

**Issue by staminna** [TalAter/annyang#132]
Hi
I am having an issue getting the regex example to work.

'calculate :quarter stats': {'regexp': /^calculate (January|April|July|October) stats$/, 'callback':
}

Uncaught SyntaxError: Unexpected token }
assistent.js line 77

If I comment this line, annyang goes on and continues to listen and work nicely.
Can you help?

**Comment by lmangani** [comment]
You have omitted the callback function itself (calculateFunction) - the full example is:

<pre>
var calculateFunction = function(month) { console.log(month); }
var commands = {
  // This example will accept any word as the "month"
  'calculate :month stats': calculateFunction,
  // This example will only accept months which are at the start of a quarter
  'calculate :quarter stats': {'regexp': /^calculate (January|April|July|October) stats$/, 'callback': calculateFunction}
}
</pre>

**Comment by TalAter** [comment]
Thanks @lmangani 
@staminna Does that solve it? If you are still having an issue, please reopen and provide more details (full code), we'll try and help.

**Comment by hasan3ysf** [comment]
I tried the below, but the optional word (the) became a mandatory one!:

    'calculate (the) :quarter stats': {
                      'regexp': /^calculate (January|April|July|October) stats$/,
                      'callback': function(quarter){alert(quarter);}
                    }

**Comment by TalAter** [comment]
@hasan3ysf When using regular expressions, the only things that counts for matching purposes is what you put in under 'regexp' (`/^calculate (January|April|July|October) stats$/`). The key you entered (`calculate (the) :quarter stats`) for referring to this command is just a name and isn't used for matching with what the user says
