### ISSUE TITLE
Handling of spoken "newline"

### ISSUE THREAD

**Issue by idupree** [TalAter/annyang#134]
When I speak "newline", speech recognition returns "\n" (a newline) rather than the word.  Unfortunately `results[i].trim();` deletes the newline character so I can't match it.  One possible fix, which I've been using, is `results[i].replace(/^[ \t]*/, '').replace(/[ \t]*$/, '');` to trim spaces but not newline characters.

**Comment by TalAter** [comment]
Hi @idupree 

My apologies for the long time it took me to get back to you.

I am not sure I understand your request? If this is still relevant, please reopen the issue and provide more information... preferably with a code sample.

Thank you.

**Comment by TalAter** [comment]
Have you tried defining your commands using a regular expression? https://github.com/TalAter/annyang/tree/master/docs#using-regular-expressions-in-commands

Does that help?

**Comment by idupree** [comment]
@TalAter: Yes, I have tried that. It does not help because, as you can see from https://github.com/TalAter/annyang/blob/24f6ee218091e/annyang.js#L103-111 , trim() is called on the input before the regexp is exec()'ed on the trimmed input.
