### ISSUE TITLE
Annyang to control gpio pins of raspberry pi 

### ISSUE THREAD

**Issue by swapnillubal** [TalAter/annyang#137]
Can i use annyang to control the gpio pins by running python coded files on raspberry pi 2??If yes ..How??
Im doing a home automation project in  which  we would give voicecommand to cntrl gpio pins..

**Comment by lmangani** [comment]
You could try pair Annyang to something like [zkgpio.js](https://github.com/zetakey/zkgpio.js)

**Comment by swapnillubal** [comment]
ok thnks for reply... that would be wrking for single devices(a LED bulb)
connected.. but wt if i need to run a python script ...i actually wanted to
run python files... which wud cntrl my gpio pins ..those python files are
using gpio libraries ... Even if the annyang would snd a command to run the
python file in the terminal.. it wud be.. cool.. if u hve any other
suggestion.. then let me know.. :)
