### ISSUE TITLE
Electron.atom.io

### ISSUE THREAD

**Issue by wizardsambolton** [TalAter/annyang#138]
Is there anyway to use annyang with electron.atom.io

**Comment by lmangani** [comment]
From the project description:
```Electron uses web pages as its GUI, so you could also see it as a minimal Chromium browser, controlled by JavaScript.```

@wizardsambolton point your Electron app at any annyang-enabled website and it should work

**Comment by wizardsambolton** [comment]
@lmangani I tried that it didnt seem to work...

**Comment by lmangani** [comment]
@wizardsambolton logs speak tons

**Comment by wizardsambolton** [comment]
@lmangani the weird thing is its not generating any errors

**Comment by lmangani** [comment]
@wizardsambolton will try to replicate

**Comment by wizardsambolton** [comment]
@lmangani thanks!

**Comment by lmangani** [comment]
Quickly tested and Annyang seems to work fine in Electron when executing with root permissions _(sudo npm start)_ and simply pointing the default quickstart at https://www.talater.com/annyang/ returns a jQuery issue triggered by an Annyang action, suggesting ```SpeechRecognition``` support being alright.

**Comment by wizardsambolton** [comment]
Thanks for you help!

- Sam Bolton, web developer
@wizardsambolton

**Comment by wizardsambolton** [comment]
@lmangani yep got it now thanks!

**Comment by TalAter** [comment]
Would love to see what you guys are working on :)

**Comment by TalAter** [comment]
This might also be helpful.

I created a demo Electron app that uses annyang:
https://github.com/TalAter/annyang-electron-demo

**Comment by daniel3d** [comment]
Reade here about the problem
https://www.chromium.org/developers/how-tos/api-keys
