### ISSUE TITLE
On result callback feature request

### ISSUE THREAD

**Issue by austinkregel** [TalAter/annyang#139]
I was wondering if there would be anyway to hook into an 'onresult' event. I want to be able to emit a socket.io event so I can have my server do a bit of data processing.

**Comment by TalAter** [comment]
I believe the updated result callbacks introduced in annyang v2.0.0 would do the trick.

You can find more details in the [v2.0.0 release notes](https://github.com/TalAter/annyang/releases/tag/v2.0.0) and [API docs](https://github.com/TalAter/annyang/tree/master/docs#addcallbacktype-callback-context).

If this isn't what you're looking for, please reopen the issue and provide some more details on what you're trying to accomplish.

**Comment by austinkregel** [comment]
That takes care of it for me :) thanks

**Comment by TalAter** [comment]
Glad to hear! :+1:
