### ISSUE TITLE
first-timers-only: Add test spec for annyang.removeCommands() with named variables

### ISSUE THREAD

**Issue by TalAter** [TalAter/annyang#142]
#### first-timers-only

This issue is tagged **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Thank you for your help :heart:

#### The Issue

The test specs do not currently test for removing commands when they contain [named variables](https://github.com/TalAter/annyang/blob/master/docs/README.md#commands-object) (e.g. `annyang.removeCommand('You can\'t take the :thing from me');`)

The tests described inside `describe("annyang.removeCommands", function() {…});` in *test/spec/BasicSpec.js* include a number of tests for other uses of `removeCommands()`, and should be used as a template for your code.

Add a test spec that tests that the following code removes the correct command, and only the correct command: `annyang.removeCommand('You can\'t take the :thing from me')`

*It should be very similar to the test spec for `it('should remove a single command with an optional word when its name is passed as a string in the first parameter')`*

#### Contributing to annyang

- [x] Fork the repository from the [annyang GitHub page](https://github.com/TalAter/annyang).
- [x] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/annyang.git`
- [x] Make sure you have *node.js* and *npm* installed on your machine. You can use this [guide](https://docs.npmjs.com/getting-started/installing-node) for help.
- [x] Install all of annyang's development dependencies with npm. `$ cd annyang; npm install`
- [x] Run grunt to make sure everything runs smoothly `$ grunt`
- [x] Code, code, code.
- [x] Run `$ grunt` after making changes to verify that everything still works and run the build process. Alternatively, you can just run `$ grunt watch` once, and leave that process running. It will continuously run all the tests and build the files every time you make a change to one of annyang's files. It will even *beep* if you make an error, and help you debug it.:+1:
- [x] Before committing your changes, the last step must always be running `$ grunt`. This makes sure everything works, and all files are kept up to date with your changes.
- [x] Once you've made sure all your changes work correctly, and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [x] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/annyang](https://github.com/YOUR-USER-NAME/annyang)) and create a pull request for your changes.
- [x] Makes sure your pull request describes exactly what you changed and references this issue (just include the issue number in the title like this: #49)

#### About the tests

annyang is tested using [Jasmine](http://jasmine.github.io/2.0/introduction.html).

BasicSpec.js contains a series of spec groups (e.g. `describe('a spec group', function() {})`) which each contain 1 or more specs (e.g. `it('should do stuff', function() {})`). Some of the spec groups also contain some code which runs before each spec (`beforeEach(function() {})`).

To simulate Speech Recognition in the testing environment, annyang uses a mock object called [Corti](https://github.com/TalAter/Corti) which mocks the browser's SpeechRecognition object. Corti also adds a number of utility functions to the SpeechRecognition object which simulate user actions (e.g. `say('Hello there')`), and allow checking the SpeechRecognition's status (e.g. `isListening() === true`).

**Comment by siawyoung** [comment]
Hi! Can I take this up? I've been looking for a project to contribute to, and this seems like a great way to start :)

**Comment by TalAter** [comment]
Merged #146 .
Thanks @siawyoung, looks great!
