### ISSUE TITLE
first-timers-only: Add test spec to make sure named variables only match single words

### ISSUE THREAD

**Issue by TalAter** [TalAter/annyang#144]
#### first-timers-only

This issue is tagged **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Thank you for your help :heart:

#### The Issue

The test specs do not currently test to make sure commands with [named variables](https://github.com/TalAter/annyang/blob/master/docs/README.md#commands-object) (e.g. `annyang.addCommands({'Time for some :description heroics': myFunction});`) only match a single word.
Named variables should match any sentence with **exactly one** word replacing the named variable (e.g. *:description*), such as: '*Time for some thrilling heroics*', but not '*Time for some thrilling and fun heroics*' or '*Time for some heroics*'

The tests described inside `describe("annyang.addCommands", function() {…});` in *test/spec/BasicSpec.js* include a number of tests for other uses of `addCommands()`, and should be used as a template for your code.

Add a test spec that tests that the following code matches the correct commands only: `annyang.addCommands({'Time for some :description heroics': function() {}});`

*It should be very similar to the test spec for `it('should match commands with named variables')`*

#### Contributing to annyang

- [x] Fork the repository from the [annyang GitHub page](https://github.com/TalAter/annyang).
- [x] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/annyang.git`
- [x] Make sure you have *node.js* and *npm* installed on your machine. You can use this [guide](https://docs.npmjs.com/getting-started/installing-node) for help.
- [x] Install all of annyang's development dependencies with npm. `$ cd annyang; npm install`
- [x] Run grunt to make sure everything runs smoothly `$ grunt`
- [x] Code, code, code.
- [x] Run `$ grunt` after making changes to verify that everything still works and run the build process. Alternatively, you can just run `$ grunt watch` once, and leave that process running. It will continuously run all the tests and build the files every time you make a change to one of annyang's files. It will even *beep* if you make an error, and help you debug it.:+1:
- [x] Before committing your changes, the last step must always be running `$ grunt`. This makes sure everything works, and all files are kept up to date with your changes.
- [x] Once you've made sure all your changes work correctly, and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [x] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/annyang](https://github.com/YOUR-USER-NAME/annyang)) and create a pull request for your changes.
- [x] Makes sure your pull request describes exactly what you changed and references this issue (just include the issue number in the title like this: #49)

#### About the tests

annyang is tested using [Jasmine](http://jasmine.github.io/2.0/introduction.html).

BasicSpec.js contains a series of spec groups (e.g. `describe('a spec group', function() {})`) which each contain 1 or more specs (e.g. `it('should do stuff', function() {})`). Some of the spec groups also contain some code which runs before each spec (`beforeEach(function() {})`).

To simulate Speech Recognition in the testing environment, annyang uses a mock object called [Corti](https://github.com/TalAter/Corti) which mocks the browser's SpeechRecognition object. Corti also adds a number of utility functions to the SpeechRecognition object which simulate user actions (e.g. `say('Hello there')`), and allow checking the SpeechRecognition's status (e.g. `isListening() === true`).

**Comment by evaldosantos** [comment]
I would like to pick it up. Will update you with results tomorrow.

**Comment by TalAter** [comment]
Great! Let me know if you need any help.

**Comment by TalAter** [comment]
Fixed by @evaldosantos in #151
