### ISSUE TITLE
first-timers-only: Add test to make sure resultNoMatch isn't called when command matched

### ISSUE THREAD

**Issue by TalAter** [TalAter/annyang#152]
#### first-timers-only

This issue is tagged **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Thank you for your help :heart:

#### The Issue

- Callbacks added using `annyang.addCallback('resultNoMatch', aFunction)` will be called when a sentence a user said doesn't match any of the currently registered commands.
- Callbacks added using `annyang.addCallback('resultMatch', aFunction)` will be called when a sentence a user said does match any of the currently registered commands.
- Callbacks added using `annyang.addCallback('result', aFunction)` will be called when a user has said something whether it matches any of the currently registered commands or not.

The test specs do not currently test to make sure `'resultNoMatch'` callbacks don't get called when a match is found.

The tests described inside `describe("annyang.addCallback('resultNoMatch')", function() {…});` in *test/spec/BasicSpec.js* include a test to make sure it is called when there is no match, and should be used as a template for creating a test for what happens when there is a match.

Add a test that verifies this condition:
````javascript
it('should add a callback which will not be called when result returned from Speech Recognition matches a command')
````

#### Contributing to annyang

- [x] Fork the repository from the [annyang GitHub page](https://github.com/TalAter/annyang).
- [x] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/annyang.git`
- [x] Make sure you have *node.js* and *npm* installed on your machine. You can use this [guide](https://docs.npmjs.com/getting-started/installing-node) for help.
- [x] Install all of annyang's development dependencies with npm. `$ cd annyang; npm install`
- [x] Run grunt to make sure everything runs smoothly `$ grunt`
- [x] Code, code, code.
- [x] Run `$ grunt` after making changes to verify that everything still works and run the build process. Alternatively, you can just run `$ grunt watch` once, and leave that process running. It will continuously run all the tests and build the files every time you make a change to one of annyang's files. It will even *beep* if you make an error, and help you debug it.:+1:
- [x] Before committing your changes, the last step must always be running `$ grunt`. This makes sure everything works, and all files are kept up to date with your changes.
- [x] Once you've made sure all your changes work correctly, and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [x] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/annyang](https://github.com/YOUR-USER-NAME/annyang)) and create a pull request for your changes.
- [x] Makes sure your pull request describes exactly what you changed and references this issue (just include the issue number in the title like this: #49)

#### About the tests

annyang is tested using [Jasmine](http://jasmine.github.io/2.0/introduction.html).

BasicSpec.js contains a series of spec groups (e.g. `describe('a spec group', function() {})`) which each contain 1 or more specs (e.g. `it('should do stuff', function() {})`). Some of the spec groups also contain some code which runs before each spec (`beforeEach(function() {})`).

To simulate Speech Recognition in the testing environment, annyang uses a mock object called [Corti](https://github.com/TalAter/Corti) which mocks the browser's SpeechRecognition object. Corti also adds a number of utility functions to the SpeechRecognition object which simulate user actions (e.g. `say('Hello there')`), and allow checking the SpeechRecognition's status (e.g. `isListening() === true`).

**Comment by TalAter** [comment]
Closed by @theotow 
Awesome work :+1:

**Comment by kentcdodds** [comment]
Perfect `first-timers-only` issue! Thanks for doing this for the community :-D

**Comment by TalAter** [comment]
Thanks @kentcdodds 
Your article was an inspiration.
