### ISSUE TITLE
Start & Stop does not work appropriately

### ISSUE THREAD

**Issue by drdevnull** [TalAter/annyang#162]
Great script! Looks like I found a bug:

Context: I have an application that listens to a changing set of commands every time a verbal command is given. The flow is:

1- start listening with commandListA
2- hear command
3- stop listening & remove commandListA
4- execute the command
5- start listening with commandListB
...etc.

To make this happen, I've been starting and stopping annyang using initializeVoiceInput and disableVoiceInput functions. Below are two coffeescript funcs that I'm using...

```
  initializeVoiceInput: ->
    annyang.addCommands @modalCommands
    annyang.start()

    annyang.addCallback 'error', ->
      alert 'There was an error!'
    annyang.addCallback 'errorNetwork', ->
      alert 'There was an errorNetwork!'

  disableVoiceInput: ->
    annyang.pause()
    annyang.removeCommands()
    # ----------> The abort() here makes all the difference <------------------------
    annyang.abort()

```
Basically, if I don't use the abort() function the application ONLY WORKS THE FIRST TIME!

When I use the abort() function, application works as intended, but I get a ton of 'error' callbacks.

In more detail:
"addCommand, listen, pause, removeCommand" pattern does not work beyond the first set of commands registered. The first set of commands stop working after remove command as expected, but the new set of commands registered do not work 100%. They work maybe 5% of the time and they work intermittently. I have tested this for about 6-7 hours for a wide range of commands. The behaviour is consistent.

"addCommand, listen, pause, removeCommand, abort" pattern works, but throws up errors. I have not tested it as extensively. With this pattern, any set of commands entered seem to be comprehended with the same level of accuracy.

Note - I do occasionally get network erros, but the errors thrown are mostly unspecificed.

Feel free to ask any questions. I'd like to help you fix this problem as I intend to use your tech extensively.

Again, thanks for putting it together

**Comment by TalAter** [comment]
Try this in the latest version of annyang.

I believe @soney fixed this bug in v2.2.1
