### ISSUE TITLE
Use variable in commands.

### ISSUE THREAD

**Issue by Kuchiriel** [TalAter/annyang#163]
Its possible to use variable in commands?

Suppose:
var commands = {'hello :name': helloFunction};

var hello = "hello"; 
var commands = {hello + ' :name': helloFunction};

In this way, wont work, there is some way that i can make it work?

Thanks.

**Comment by TalAter** [comment]
That is a JavaScript issue, not specifically related to annyang.
When constructing an object like that you can't use an expression to define a key.

You could do this instead:
````javascript
var helloFunction = function() {}
var hello = "hello"; 
var commands = {};
commands[hello + ' :name'] = helloFunction;
````

**Comment by Kuchiriel** [comment]
Thanks @TalAter!
