### ISSUE TITLE
Chrome microphone access request doesn't go away.

### ISSUE THREAD

**Issue by charlesfries** [TalAter/annyang#173]
OS X 10.11, Chrome 48.0.2564.116

The alert that says "my-domain wants to: Use your microphone" will not dismiss when I click the Allow button. It seems to accept my response but the window then opens again immediately.

**Comment by lmangani** [comment]
Are you using https://?

**Comment by charlesfries** [comment]
I'm actually just connected to my home server where my script is running. Just using http

**Comment by charlesfries** [comment]
Just tested on my Windows 10 VM and it works. Must be something wrong with my configuration

**Comment by jamesarm97** [comment]
I have am still fighting it. I wish there was an easy way to compile chromium without that setting. Yes it goes away with https *but* then you cannot make any other script calls to non-https sites. One of the sites I am trying to get info from does http only. This is when the annyang is trying to be implemented with a magic mirror project. 

--
James Armstrong

**Comment by lmangani** [comment]
there are good reasons for this being in place, but also switches in Chrome to override them - I don't think its good to advice this with examples as those quickly change and are insecure, but you should be able to google them up and try them easily.

**Comment by charlesfries** [comment]
I've found this page chrome://settings/contentExceptions#media-stream-mic

But how do I whitelist my server's IP?

**Comment by jamesarm97** [comment]
I already tried whitelisting my local ip and it showed in the list but it still asks or seemed to ignore that. There is no button or way to whitelist your ip on that page. I think it is only done if it prompts to allow and you select remember or something like that. Still very much a pain at this point and unusable in my application (which relies on http data from other sources and some to no have https access so when I try and switch everything to https it fails.

**Comment by artforlife** [comment]
I am also having this same issue. What is interesting, my local environment works well; however, when I push it to production (AWS EC2 instance), the site repeatedly asks me to allow or block the usage of microphone every 5-10 seconds. Does anyone know why this happens?

**Comment by lmangani** [comment]
Any reason why you decided to copy-paste the very same text in 3 existing issues rather than open your own with proper details?

This being said, you need to describe your setup and settings in more detail. Are you using ```https``` in production?
