### ISSUE TITLE
Repeated confirmation of microphone usage in chromium

### ISSUE THREAD

**Issue by mrigo** [TalAter/annyang#179]
Hi!
I'm trying to use annyang on my raspberry pi using Chromium.

## Expected Behavior
When I load my web page with my angualrjs app, If I agree the first time then Chromium doesn't need my permission anymore.

## Current Behavior
Chromium ask me forever confirmation of microphone usage.

## Context
The only solution is to block the mic, but I need the permission..

## Your Environment

* Version used: 2.2.1
* Browser Name and version: Chromium 48
* Operating System and version (desktop or mobile): Raspberry pi 2

**Comment by lmangani** [comment]
Are you using https:// ?

**Comment by mrigo** [comment]
No, I'm on localhost..

**Comment by sdkcarlos** [comment]
@mrigo  due to "security" reasons, chrome will prompt the permission everytime is requested **if you're serving your file with http**. You need to force a **https** connection buying or creating a self signed ssl certificated.

This point is very clear in the homepage of the library.

**Comment by Totoajax** [comment]
If you have another website open that uses the microphone (for example www.talater.com/annyang/), it seems like those will fight for the rights and only one of them can win. So both sites will be spamming, requests
