### ISSUE TITLE
Using https:// but microphone permission doesn't even appear

### ISSUE THREAD

**Issue by wumpeth** [TalAter/annyang#185]
I had the repeating microphone permission problem that this forum helped me fix, then I got an SSL and now it no longer even appears! Why not!

**Comment by TalAter** [comment]
Try clicking the video camera icon on the edge of Chrome's address bar, you may have it set there. Try also clicking the Manage microphone access button there to see if you have it set there.

![](http://i.imgur.com/UQC1STL.png)

If this doesn't work, please provide more detail about your problem if you want people here to be able to help you. For example, you did not even mention if the permission is currently always on, or off.
