### ISSUE TITLE
DIFFERENT microphone permission problem

### ISSUE THREAD

**Issue by wumpeth** [TalAter/annyang#186]
My site earthcurio.us uses annyang.min.js for some simple voice-recognition. At first my website was hosted on Bluehost, and the microphone permission alert box that appears by the address bar in Chrome would either not go away when the buttons were clicked, or would reappear 20 seconds or so later.

Now I've switched to Namecheap and purchased an SSL, because I was told https:// would remember the user preference. Now, however, the box doesn't even appear anymore to ask for permission, and thus the speech-activated parts of my site don't work!

I've been told it could be because of my site linking to other places using http:// but I'm pretty sure I've checked and fixed all the links. Can anyone help fix this?
The permission box should appear at any of the pages other than the index.html.

I'm using a Macbook Pro with El Capitan, and I'm using Google Chrome.
www.earthcurio.us

**Comment by lmangani** [comment]
Check your console log for errors. You are probably trying to load the library using http:// (insecure)

**Comment by wumpeth** [comment]
There are actually no errors listed!

**Comment by TalAter** [comment]
Could you include a link where we could see the problem?
I looked at www.earthcurio.us and it doesn't include annyang in it.

**Comment by wumpeth** [comment]
www.earthcurio.us/france.html, or www.earthcurio.us/tanzania.html, or any of the country pages

**Comment by lmangani** [comment]
Unless i'm missing something... you fail to initialize annyang in your init function (js/script.js)
If i patch the initializer in a clone, annyang gets permissions and starts listening.

PS=You're building something nice! But i would **strongly** advice against using raw WAV files for audio streaming!

**Comment by wumpeth** [comment]
You're right, in all my messing around I deleted the most important stuff. 
Thanks!

Also, what would you suggest instead of .wav, and why?

**Comment by lmangani** [comment]
MP3 will provide the best [support across browsers](http://www.w3schools.com/html/html5_audio.asp), and huge savings in bandwidth and server costs. Just convert your audio with sox and replace .wav with .mp3 across your code, no other changes needed. Good luck!
