### ISSUE TITLE
Annyang in Angular's controller does not work as expected

### ISSUE THREAD

**Issue by kelvien** [TalAter/annyang#189]
Hello,

This issue is pretty straight forward, I have started Annyang in a controller and it works as expected, the commands' callback function is able to apply the changes to my view through $rootScope.$apply.
However when I move to another state and come back to my initial state that has the Annyang commands, the callback function cannot apply the changes.

Here is the demo in plunkr:
https://plnkr.co/edit/7cQmPjcFHPcYkPCry4YA

My friend helped me to solve this, and this is the solution he came up:
http://plnkr.co/edit/1Bsqt2NbBK9z3QkgVD3v?p=preview

Basically he put the commands in the run function. This works fine, but I would rather have my commands to be instantiated in each controller so that my controller can have full control of what to set and get through the callback function.

What am I missing?

Steps to reproduce in my plunkr:
https://plnkr.co/edit/7cQmPjcFHPcYkPCry4YA
Open state 1 -> allow mic access -> say "hello" or "test" -> expect changes in the view (Works fine) -> go to state 2 -> come back to state 1 -> say "hello" or "test" -> changes are not reflected, although annyang still detects the commands

Please help me solve this issue

**Comment by artforlife** [comment]
Greetings,

I am also trying to use Annyang in an angular controller. Have you been able to resolve your issues? Is this a path worth following? 
Is it as simple as adding the Annyang instantiation code into the controller? Or is there more setup needed?

**Comment by kelvien** [comment]
I can't resolve this particular issue. I think it is better to instantiate Annyang from a Service. There's a lot of example in the internet that uses Annyang as a service.

**Comment by oziee** [comment]
$rootScope.$digest(); instead of $rootScope.$apply(); works
