### ISSUE TITLE
CDN not functional

### ISSUE THREAD

**Issue by ctrlaltdylan** [TalAter/annyang#190]
Unable to pull the annyang 2.4.0 from the example documentation in the cdn form:

GET file://cdnjs.cloudflare.com/ajax/libs/annyang/2.4.0/annyang.min.js net::ERR_FILE_NOT_FOUND

## Expected Behavior

Expecting to be able to pull the annyang script from the CDN.

## Current Behavior

GET file://cdnjs.cloudflare.com/ajax/libs/annyang/2.4.0/annyang.min.js net::ERR_FILE_NOT_FOUND

## Steps to Reproduce (for bugs)

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>title</title>
  </head>
  <body>
    <script src="//cdnjs.cloudflare.com/ajax/libs/annyang/2.4.0/annyang.min.js"></script>
    <script>
    if (annyang) {
      // Let's define a command.
      var commands = {
        'hello': function() { alert('Hello world!'); }
      };

      // Add our commands to annyang
      annyang.addCommands(commands);

      // Start listening.
      annyang.start();
    }
    </script>
  </body>
</html>
```

## Your Environment

* Version used: 2.4.0
* Browser Name and version: Latest Chrome
* Operating System and version (desktop or mobile): Ubuntu 
* Link to your project:

**Comment by lmangani** [comment]
Hi @ctrlaltdylan 
Loading the script using ```//``` will translate to ```file://``` when running off the filesystem.
You should have no issues when running your app on a webserver, or use ```https://``` when loading the library to receive the expected results.

**Comment by ctrlaltdylan** [comment]
Learned you need a webserver. Doh!

Works perfect now. Excellent library thank you!
