### ISSUE TITLE
Automatic npm releasing from Travis

### ISSUE THREAD

**Issue by v12** [TalAter/annyang#191]
I found that, despite proper versioning in the repository, the package itself is not being published to npm registry. A solution to that can be [Travis CI automatic releasing](https://docs.travis-ci.com/user/deployment/npm/). :rocket: 

For instance, Travis CI can be configured to release only tagged commits from master branch (see details [here](https://docs.travis-ci.com/user/deployment/npm/#What-to-release)).

It's quite common practice to keep npm registry updated because neither going to the repository each time to download the library nor specifying exact repository with version tag in dependencies are effective ways of working with the package. :+1: 

Feel free to comment or ask questions :wink:

**Comment by TalAter** [comment]
Thanks for the suggestion!

Looking forward to seeing it in action with the next release
