### ISSUE TITLE
the js does not seem to be able to listen on android phone, browser works great

### ISSUE THREAD

**Issue by kumarsubodh** [TalAter/annyang#199]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by TalAter** [comment]
Incomplete bug report

**Comment by DanielRuf** [comment]
Not yet supported on Android http://caniuse.com/#feat=speech-recognition
