### ISSUE TITLE
Unable to find Cloudflare file

### ISSUE THREAD

**Issue by BlueAffinity** [TalAter/annyang#200]
I'd like to first start off by saying that I am very rusty in my html coding; and even rustier when it comes to javascript in my html.

I tried inserting the canned code from the annyang homepage into my HTML; and when I run the HTML in Chrome; the debugger says

 file://cdnjs.cloudflare.com/ajax/libs/annyang/2.4.0/annyang.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND

Am I missing something crucial here? I am just trying to get this to work on the most basic level to understand it.

**Comment by lmangani** [comment]
Hi @BlueAffinity 

Just replace ```file://``` with ```https://``` to load the resource from the network as opposed to your local filesystem. Hope this helps!

**Comment by TalAter** [comment]
Thanks @lmangani 

@BlueAffinity Even during development, you should be running your html on a local server, and not just opening the html in your browser directly. Speech Recognition, and many other things, don't work as well like that.
