### ISSUE TITLE
Robustness of annyang in Continuous Listening.

### ISSUE THREAD

**Issue by arthchan2003** [TalAter/annyang#202]
Hi, 

I was playing with annyang.  For the most part it is working okay.  But for every 5-6 minutes or so, the API would become very irresponsive.  By "responsive", specifically I mean when turning on debug mode, there is not recognition result come back and line 106 of annyang.js just doesn't give any response. (So you can rule out it as a parsing issue.)

Another measure I tried is to reduce  the limit of timeSinceLastStart at line 222
i.e.    changing this line if (timeSinceLastStart < 1000) {    
to                                                                                                                            
          if (timeSinceLastStart < 10) {

In fact, my 5-6 mintue quote actually come from this more aggressive time out scheme.  

I apologize beforehand I couldn't repeat the issue, but feel curious if anyone has encountered similar problem.   Also would anyone share me any tips, I was hoping this package can provide continuous listening for more than 10 minutes.  I just wonder who achieve something similar with annyang. 

Art

**Comment by TalAter** [comment]
I found that Chrome's Speech Recognition implementation has a tendency to abort and stop listening after a while. This is unrelated to annyang.
What annyang does to combat this, is to restart Speech Recognition automatically when this happens.

I am not sure if you mean that after 5-6 minutes the browser's Speech Recognition no longer works, or annyang.

You can attach events to the browser's own Speech Recognition object, bypassing annyang to see if it still listens and annyang just ignores it. I would be curious to see what you find.

````javascript
var sr = annyang.getSpeechRecognizer();
sr.addEventListener('result', function(event) {console.log(event);})
````

**Comment by arthchan2003** [comment]
Tal: Thank your for the info on debugging.  I hear you.  It does sound like an intrinsic problem of Chrome's speech recognition instead of issues on annyang.  I would first dump the events and see if I can diagnose the problem better.  Perhaps send out another mail.  Anyhow, thanks for your time to answer the questions.
