### ISSUE TITLE
Not asking for mic permissions repeatedly in HTTP 

### ISSUE THREAD

**Issue by prateek1985** [TalAter/annyang#205]
## Expected Behavior

Hi I am using annyang in HTTP and for fast response I have set continuous mode to be off in annyang but chrome has asked my permission for mic only once and rest all the time its working fine without asking any permission. But as mentioned in lots of [threads](https://github.com/TalAter/annyang/issues/182) that in HTTP the browser would continuously ask the user for permission after every sentence
## Context

So I want to know is it useful and safe to make continuous mode off in HTTP because I am using annyang in some big open source software and I have to make sure that it doesn't ask for permission again and again.

## Your Environment

* Version used: 2.4.0
* Browser Name and version: Chrome 50.0.2661.94 (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 14

**Comment by TalAter** [comment]
Can you provide a code sample that shows it on HTTP in non-contiuous mode without re-asking for permission every time? I haven't seen that before? Unless you set it in the browser's permissions to trust that site always.

**Comment by prateek1985** [comment]
<html>
<body>
<script src="annyang.js"></script>
<script src="speechkitt.js"></script>
<script src = "jquery-2.1.4.min.js"></script>
<script>
if (annyang) {

  var addText = function(tag) {
     document.getElementById("divTag").innerHTML = tag+" ";
     
  }

  // Add our commands to annyang
  annyang.addCommands({
      '*tag': addText,
  });

  SpeechKITT.annyang();
  annyang.setLanguage('en-GB');
  annyang.debug(true);
  annyang.start({ continuous: false });
  
  SpeechKITT.setInstructionsText("Say 'voice mode' followed by your Query");
 
  SpeechKITT.setStylesheet('themes/flat-pomegranate.css');
  // Render KITT's interface
      SpeechKITT.vroom();

}
</script>
</body>
<div id = "divTag"></div>
</html>

 
Above is code sample that I am using via speech KITT API and I am running this in apache2 localhost.

**Comment by artforlife** [comment]
I am also having this same issue. What is interesting, my local environment works well; however, when I push it to production (AWS EC2 instance), the site repeatedly asks me to allow or block the usage of microphone every 5-10 seconds. Does anyone know why this happens?

**Comment by Shehanka** [comment]
I have same error, In localhost it's working but without local host It wasn't working
