### ISSUE TITLE
Capitals and Lowercase No Match

### ISSUE THREAD

**Issue by thiinkbox** [TalAter/annyang#207]
Im wondering is there a way to bypass or ignore capitals? for example if i search the word "Place" the debug shows "place" and fails to identify it.. Im using a command to checkbox options.

'select *extra' : function(extra){
var
index = -1,
x = document.getElementsByClassName('facetwp-checkbox');
for( var i=0; i<x.length; i++) {
if( x[i].innerHTML.indexOf(extra) > -1){
index = i;
break;}}
if(index > -1){
x[i].className += " checked";
FWP.autoload();
}}

Any help is appreciated thanks

**Comment by JeffZhang02747** [comment]
Not sure what your code is doing. However, if you want to ignore the capitals, just convert the "Place" to lowercase, also convert the argument extra to lowercase. Then do the comparison.

**Comment by TalAter** [comment]
Just like @JeffZhang02747 said, it seems like something that can be solved in your code by changing the case or making your queries case insensitive. I am not sure what you mean by "search the word Place".

If you still require help, it can be helpful if you provide the simplest code possible that can reproduce your issue.
