### ISSUE TITLE
Should be able to trigger commands when speech recognition is off

### ISSUE THREAD

**Issue by thurt** [TalAter/annyang#209]
I would like to write tests to ensure each annyang command performs the callback operation as intended on the webpage. Unfortunately, I am not able to get commands to trigger when annyang isn't listening.

## Expected Behavior
should be able to use `annyang.trigger` to fire callback functions for the purposes of testing when there may be no microphone or internet connection.

## Current Behavior
described above.

## Possible Solution
Don't check if `annyang.isListening` in `annyang.trigger` ??

## Context
described above.

## Your Environment
n/a

Edited

**Comment by TalAter** [comment]
I actually wrote a library for [testing speech recognition](https://github.com/TalAter/corti) which emulates the browser's speech recognition API for this purpose exactly. It is called [Corti](https://github.com/TalAter/corti), and you can see it in action in [Speech KITT](https://github.com/TalAter/SpeechKITT/blob/master/test/spec/2_UISpec.js#L37) and annyang itself.
