### ISSUE TITLE
Allow command object to work for commands which do not have a regexp

### ISSUE THREAD

**Issue by thurt** [TalAter/annyang#210]
I want to attach some other application-related properties to my command object.

Therefore, command object signatures that look like
```javascript
'word': function() { ... }
```
I am converting to signatures like
```javascript
'word': {
  callback: function() { ... },
  otherProp: 1
}
```
The problem is that `annyang` doesn't treat these as equivalent. It will not load command objects like shown in the second signature. It will only load command objects which look like:
```javascript
':word': {
  regexp: 'word',
  callback: function() { ... },
  otherProp: 1
}
```

## Expected Behavior
It should accept command objects like either of the first two shown above. This should work regardless of whether there is a regexp requirement or not.

## Current Behavior
described above. 

## Possible Solution
haven't looked yet 

## Steps to Reproduce (for bugs)
described above

## Context
described above

## Your Environment
n/a

**Comment by TalAter** [comment]
Interesting.

Can you share and example of why and how you need to use the extra properties on the command objects? This should help in implementing this in a way that will benefit the most users.

Thank you

**Comment by TalAter** [comment]
See #211
