### ISSUE TITLE
Can this be used to capture the sentences spoken rather than the commands?

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [TalAter/annyang#213]
Hi,

I want to know if the plugin can be used to capture the sentences spoken by the user. I should be able to capture the text when the user speaks and show in a text area or a div. As far as I have seen it uses only commands to identify what action to do, is there a way to capture the speech and just display it?

**Comment by TalAter** [comment]
Great question.

I just added it to the FAQ, along with an answer containing sample code: https://github.com/TalAter/annyang/blob/master/docs/FAQ.md#can-annyang-be-used-to-capture-the-full-text-spoken-by-the-user
