### ISSUE TITLE
Letter versus words

### ISSUE THREAD

**Issue by andrew--grant** [TalAter/annyang#214]
My expectation was that if I provide a command for, say, the letter 'a', I could then show the locations of the note 'a' on an image of a guitar fretboard. This didn't work at all.

So I tried the word 'ayy' and other such variations, these didn't solve my problem. I was able to create working commands for 'c' (using 'sea') and 'd' (using dee). Not, however, with 'g' (using jee and similar) or 'f' (using eff and similar).

I suppose my question/issue is how to use this library, if possible , for letters, instead of words? Trying to 'fool' it doesn't appear to be of much use.

**Comment by jchook** [comment]
The recognition engine appears to do very well with numbers and ordinals... just throwing it out there.

**Comment by TalAter** [comment]
How it recognizes it is based on the browser's recognition engine.

We could improve it for cases like this by defining grammar (#11), which hasn't been implemented in annyang yet.
