### ISSUE TITLE
The 'result' event of annyang is called many number of times.

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [TalAter/annyang#216]
hi,

I have a button to indicate speech recognition active. When the button is clicked, the speech is recognized and when clicked again, it is stopped. So in that, I am calling the 'start' method and then the 'pause' on page load just to wait to recognize until the button is clicked. On button click, I am calling resume method to start listening. Again, when the button is clicked, I am calling the pause method. 

When the same resume and pause is done for more than one time, the result event which fires when a phrase is recognized, is also called that many times the resume method is called.

**See sample below.**

        if (annyang) {
        annyang.start();
        annyang.pause();
        $('.speak-button').on('click', function () {

            if ($(this).hasClass('listening')) {
                $(this).removeClass('listening').addClass('not-listening');
            } else {
                $(this).removeClass('not-listening').addClass('listening');
            }

            if ($(this).data('on') === false) {
                annyang.resume();

                annyang.addCallback('result', function (phrases) {
                    console.log('User Spoke - ', phrases[0]);
                    console.log('Could Be - ', phrases);
                    $('.speech-text').html($('.speech-text').html() + phrases[0]);
                });

                annyang.addCallback('error', function (err) {
                    console.log('There was an error in Annyang!', err);
                });

                $(this).data('on', true);
            } else {
                $(this).data('on', false);
                annyang.pause();
            }
        });

**Console Output:**

When I had clicked the button twice

User Spoke -   testing
Index:80 Could Be -  [" testing", " Justin", " Jashn", " testingken"]
Index:79 User Spoke -   testing
Index:80 Could Be -  [" testing", " Justin", " Jashn", " testingken"]

When I had clicked the button thrice
User Spoke -   hello
Index:80 Could Be -  [" hello", " hallo", " helo", " hell"]
Index:79 User Spoke -   hello
Index:80 Could Be -  [" hello", " hallo", " helo", " hell"]
Index:79 User Spoke -   hello
Index:80 Could Be -  [" hello", " hallo", " helo", " hell"]

This happens even when I try to abort it when not listening and trying to start it again.

Please help me on how to get this working.

**Comment by mcollovati** [comment]
You should initialize your callbacks only once (before start for example), not at every button click.


```
  if (annyang) {
     annyang.addCallback('result', function (phrases) {
         ...
     });
     annyang.addCallback('error', function (err) {
        ...
     });
    annyang.start();
    annyang.pause();
    $('.speak-button').on('click', function () {
     ...
   }
}
```

Or else you must remove them on pause (anyang.removeCallback)

```
  if (annyang) {
      ...
      $('.speak-button').on('click', function () {
          var resultCallback = function (phrases) { ... };
          var errorCallback = function(err) { ... };
         
         if ($(this).data('on') === false) {
            annyang.resume();
            ...
            annyang.addCallback('result', resultCallback);
            annyang.addCallback('error', errorCallback);
           ....
        } else {
              annyang.pause();
              annyang.removeCallback('result', resultCallback);
               annyang.removeCallback('error', errorCallback);  
        }
      }
  }
```

**Comment by TalAter** [comment]
Thanks @mcollovati :+1: 

Events can have multiple listeners on them. Your code adds another listener every time you click that button. Just add them once, or remove them when you `abort()` or `pause()` annyang
