### ISSUE TITLE
official site not working in chrome browser

### ISSUE THREAD

**Issue by MuhammadUzair** [TalAter/annyang#218]
![any](https://cloud.githubusercontent.com/assets/15572020/17103917/0919c34a-529a-11e6-9298-1be842662589.jpg)
## official site not working in chrome browser

Browser keeps asking me whether I would allow or deny the page to use the microphone.
When I allow them then nothing happen.When i refresh page it come again.
 

## Environment

Google Chrome	= 53.0.2772.0 (Official Build) canary (64-bit)
OS	                        =Windows 10
JavaScript	                =V8 5.3.256
Flash	                =22.0.0.192

**Comment by TalAter** [comment]
Do you have a microphone on that machine? Is it configured correctly? Your screenshot says: "Microphone: None available"

**Comment by MuhammadUzair** [comment]
It's microphone configration issue.

Thank you for Respond.
