### ISSUE TITLE
Annyang not able to listen after dialog window OR pop window opens from parent window

### ISSUE THREAD

**Issue by Mahesh-Virupa** [TalAter/annyang#219]
Annyang not able to listen after a dialog or pop up window opens.
When I open a dialog or pop up window, annyang stops listening the command. Not sure what is the issue here.
## Expected Behavior
It should keep listening as dialog or pop up window is a part of parent window itself. 

## Current Behavior
It is not keep listening when a dialog or pop up window opens.

**Comment by Mahesh-Virupa** [comment]
Hi All,

Any update on this ?

Thanks,
Mahesh

**Comment by TalAter** [comment]
Can you provide a way to reproduce this issue? 
There is simply too much info missing for anyone to be able to check this
