### ISSUE TITLE
Unable to use Annyang on Mac in Electron

### ISSUE THREAD

**Issue by SpyMachine** [TalAter/annyang#220]
I'm trying to build an Electron app using Annyang on my Mac (10.11.5) but it is failing. I've done some rudimentary debugging and it looks like Annyang keeps trying to restart itself but I haven't figure it out beyond that. 

I have tried the "annyang-electron-demo" and am getting the same results.

**Comment by TalAter** [comment]
I believe this might be due to the same issue described in #138.

For a software to use Google's Speech APIs, it needs a API key... and it looks like Electron has passed their quota. Hopefully they are working on allowing developers to use their own keys.

See the discussion in #138
