### ISSUE TITLE
recognition.onerror not passing event object to invokeCallbacks

### ISSUE THREAD

**Issue by daniel3d** [TalAter/annyang#222]
Hi i think the function recognition.onerror need to be updated
```
 recognition.onerror   = function(event) {
        invokeCallbacks(callbacks.error); // change to invokeCallbacks(callbacks.error, event);
        switch (event.error) {
        case 'network':
          invokeCallbacks(callbacks.errorNetwork);
          break;
        case 'not-allowed':
        case 'service-not-allowed':
          // if permission to use the mic is denied, turn off auto-restart
          autoRestart = false;
          // determine if permission was denied by user or automatically.
          if (new Date().getTime()-lastStartedAt < 200) {
            invokeCallbacks(callbacks.errorPermissionBlocked);
          } else {
            invokeCallbacks(callbacks.errorPermissionDenied);
          }
          break;
        }
      };
```

for example im trying to find the event error with this function but the event is not passed to the callback by passing the event object to the invokeCallbacks(callbacks.error, **event**); is fixing it not sure if it was not passed on purpose.

`	annyang.addCallback('error', function(event){
		console.log(event);
	});
`

**Comment by TalAter** [comment]
Hi @daniel3d.

Completely by coincidence, and before I even saw this issue, I added this exact feature, using this exact code in 6199791bfc33278a51c26f65d85632e7704e0d2f 😄. 

It is available in v2.5.0.
