### ISSUE TITLE
I can't use annyang api before 4pm.

### ISSUE THREAD

**Issue by ptytoo** [TalAter/annyang#224]
Hi, I am a student living in South Korea, and I'm using annyang api on my raspberry pi.
But there's a problem.
I can't use annyang api before 4pm......
After 4pm, it works perfectly. And there is no problem when I run my web page with chrome on my desktop even before 4 pm!!.... How can I solve this problem??
(I think this problem is related to local time.)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by TalAter** [comment]
Hi @ptytoo,

annyang uses the browser's speech recognition engine... In Chrome this relies on Google's speech recognition which is done in the cloud. Unlike Chrome, other programs that use the same API (like Chromium, which is probably what you are using) use their own API keys to access the speech API, and are limited to a certain number of requests per day.

Your 4 pm is probably when the daily quota starts and so the API works, once it runs out, it returns an error.

There is some more information about this in the [FAQ](https://github.com/TalAter/annyang/blob/master/docs/FAQ.md#can-annyang-be-used-in-chromium-or-electron)
