### ISSUE TITLE
Any solution for mute beep sound when the speech recognition not undestand

### ISSUE THREAD

**Issue by dpmontero** [TalAter/annyang#225]
Are there any solution for mute the beep sound of speech recognition?

Not valid mute the volume of device or speaker.

Thanks!

**Comment by TalAter** [comment]
I am guessing you are talking about the repeated beeps on mobile devices only?

We are discussing this on #194, but still haven't found a solution yet.

I am closing this as a duplicate issue. If this is wrong, please reopen and provide more details on the problem along with code to help reproduce the issue.

Thanks :+1:
