### ISSUE TITLE
Google Cloud Speech API

### ISSUE THREAD

**Issue by hdezela** [TalAter/annyang#226]
Could it be possible to use with the [Google Cloud Speech API](https://cloud.google.com/speech/) in order to overcome the daily limits on alternative browsers?

**Comment by BurakDev** [comment]
no

**Comment by evancohen** [comment]
It's not quite ready for prime time, but I'm building a speech recognition framework (with hotword detection and Google Cloud Speech): https://github.com/evancohen/sonus

My plan is to enable people to use annyang as one of the command recognition systems, but I haven't quite gotten to that work yet.

**Comment by Norbz** [comment]
With the current limitation existing on Chrome Speech API, especially when building an Electron App, this would be a great option. It would also improve Browser Support like for IE or Safari.

I think this should be discussed again :)

**Comment by TalAter** [comment]
@Norbz If you would like to tackle this, I would be happy to receive a pull request about it.
