### ISSUE TITLE
There is no function to show current version.

### ISSUE THREAD

**Issue by Kuchiriel** [TalAter/annyang#228]
It will be nice if is possible to add some function to return the software version, like:

annyang.version()

**Comment by TalAter** [comment]
Hi @Kuchiriel 

Could you explain the use case for this? Why do you need this, and how would you use it?

Understanding how it is used, helps plan a better API for annyang.

Thanks.

**Comment by Kuchiriel** [comment]
Hi @TalAter 

![](http://i.imgur.com/M5yceTz.png)

The use case is when you want to show the software version without hardcoding it. We need for debuging and logging purposes.

**Comment by TalAter** [comment]
It seems like a bit of an edge case. I'm sorry, but I try not to include features that wouldn't benefit the bulk of our users. Any addition affects the entire library, and needs to be maintained forever... so we have to make sure there's demand for it.

Does anyone else have a need for this, and can explain their need?
