### ISSUE TITLE
A way to add and remove classes for each word spoken.

### ISSUE THREAD

**Issue by peterdillon** [TalAter/annyang#229]
Looking to make a wavelength line activate (togggle class names) as words are being spoken for an effect like you see on iphone and firestick voice control devices.

This codepen is ready for this:
Ttoggling 'small-vibe' and 'big-vibe' on active speaking is what I am trying to do.
http://codepen.io/peterdillon/pen/yaPdNo

Thank you!

**Comment by TalAter** [comment]
OK, based on your use case I have added a feature that should allow you to accomplish this by listening to the `soundstart` and `result` events.

This is available starting in [annyang v2.6.0](https://github.com/TalAter/annyang/releases/tag/v2.6.0), which adds support for the `soundstart` event.

I also added an explanation with some code to the FAQ - [Can I detect when the user starts and stops speaking?](#can-i-detect-when-the-user-starts-and-stops-speaking)

**Comment by peterdillon** [comment]
This is great - thank you for all your work.
