### ISSUE TITLE
"end" callBack seems to run every 2 seconds

### ISSUE THREAD

**Issue by peterdillon** [TalAter/annyang#230]
I noticed when I loaded the pen on my android S6 with both mobile Chrome and Firefox browsers. The "speech input closing" sound was looping.
## Expected Behavior

Go back to annyang.start()
## Current Behavior

"end" callBack seems to run every 2 seconds
## Test Pen

https://codepen.io/peterdillon/pen/yaPdNo?editors=1111

**Comment by revett** [comment]
May be linked to this Android issue: https://github.com/TalAter/annyang/issues/194 👍

**Comment by peterdillon** [comment]
Yes, looks like it is... I will follow that issue. Thank you! @revett

**Comment by peterdillon** [comment]
Duplicate of:
https://github.com/TalAter/annyang/issues/194
