### ISSUE TITLE
Why SpeechRecognition not supporting in IE?

### ISSUE THREAD

**Issue by VenkateshRajan3** [TalAter/annyang#238]
Hi Team,
Could you please suggest me why this speech Recognition not supporting in IE browsers.
I am using IE 11 version.
Thanks & Regards,
Venkatesh Rajan

**Comment by debatanu-thakur** [comment]
The speech recognition api uses `webkitSpeechRecognition` javascript object which is as of now supported only in chrome and firefox. You can find more at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API).

**Comment by debatanu-thakur** [comment]
The speech recognition api uses `webkitSpeechRecognition` javascript object which is as of now supported only in chrome and firefox. You can find more at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API).

**Comment by DanielRuf** [comment]
@VenkateshRajan3 take a look at the table at http://caniuse.com/#feat=speech-recognition

**Comment by Viveksingh1313** [comment]
This is one of the best link you would find for this: https://stackoverflow.com/questions/39253574/speech-recognition-in-internet-explorer 

You can't have this feature in internet explorer. i will give you one more example- the link below is by microsoft teams describing the text-to-speech functionality by an application. Try running it on Internet Explorer, it won't work. So whoever asks you to achieve this, show this example.  
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/speechsynthesis/

**Comment by DanielRuf** [comment]
Well, IE does not get new features so it will never happen ;-)

**Comment by DanielRuf** [comment]
The new examples only work in Edge.
