### ISSUE TITLE
Possible to log what is asked?

### ISSUE THREAD

**Issue by jazzkonnen** [TalAter/annyang#239]
Is possible to log what is asked, so that we can make her more dynamic?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by TalAter** [comment]
Look at the documentation for [`annyang.addCallback('result')`](https://github.com/TalAter/annyang/tree/master/docs#addcallbacktype-callback-context) - I think this is what you are looking for.

If not, please provide more details on exactly what you are trying to do... a lot more details 😉

**Comment by jazzkonnen** [comment]
I don't think so. A user comes to the site and says something that isn't meant to be recognized. Is it possible to know what was said so I can add it. Sorry for vagueness
