### ISSUE TITLE
Multiple named variables in one command

### ISSUE THREAD

**Issue by araltasher** [TalAter/annyang#241]
I would like to be able to recognize multiple variables in one command rather than using the greedy approach

## Expected Behavior
var command = {

  'if today is :day then set the color to :color ': colorOfTheDay,

}

var colorOfTheDay = function(day, color) {

if( color == "Black" && day == "Friday"){
//do something
}
 else if( color == "Blue" && day == "Saturday"{
//another func();
}
}

**Comment by BetaStacks** [comment]
You can see an example that does this at http://jsfiddle.net/JMPerez/p30pb38z/

**Comment by TalAter** [comment]
Thanks @BetaStacks! Great demo, and works perfectly.

By the way, if you find yourself needing to do more complicated sentence recognition, you can supply annyang with regular expressions. Check out the [docs](https://github.com/TalAter/annyang/tree/master/docs#using-regular-expressions-in-commands) for this.

**Comment by zohaibarshad-ai** [comment]
Is it still Possible? 
It gives me error when using multiple named variables and accepting them in callback function
![image](https://user-images.githubusercontent.com/79120799/191862804-a9ccfefa-6dea-467c-8679-50cade730f26.png)

This is how library code looks like
![image](https://user-images.githubusercontent.com/79120799/191862925-a80338f6-5b90-4e83-8706-974d6b902e53.png)
