### ISSUE TITLE
annyang.trigger not working

### ISSUE THREAD

**Issue by BetaStacks** [TalAter/annyang#242]
I am trying to use the annyang.trigger method but it doesn't seem to be working. 

    $( "#trigger" ).click(function() {annyang.trigger('hello');});

Am I missing something?

**Comment by TalAter** [comment]
The `annyang.trigger('hello');` command looks good... might be unrelated to annyang. But it's hard to know for sure without more context.

Could you provide a complete working code sample? Perhaps a codepen?

**Comment by BetaStacks** [comment]
You were right It was my IDE. For some reason the code doesn't work when it is compiled into an external JS file, but If I put the script inline it works as expected. 

Now I just need to work out how to get the triggers to work in Safari.  :)
