### ISSUE TITLE
A Parser-blocking, cross-origin script on annyang demo website

### ISSUE THREAD

**Issue by ihabZhaika** [TalAter/annyang#243]
Hi,
i wanted to try the[ online demo ](https://www.talater.com/annyang/), on the console i get the following log

`include.preload.js:465Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details.
`
`(index):19 A Parser-blocking, cross-origin script, https://cdnjs.cloudflare.com/ajax/libs/annyang/2.5.0/annyang.min.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.`
i searched on google , and it seems because google changed few thing in google chrome , and my connection is fast enough 
So how to get it to work ?

**Comment by TalAter** [comment]
Thanks for bringing this to my attention.

I just fixed this in 675f0ebbe51deb4b5e8ff3cc1320bfc5d7495ff8
