### ISSUE TITLE
Not detected on Apple Iphone (6)

### ISSUE THREAD

**Issue by avancleef** [TalAter/annyang#244]
I tried your demo whish works fine on a old smartphone but on my Apple iPhone 6 I get no "can we use your microphone" dialog or anything... the website simply states that I need to use a other browser.

Tried Safari and Chrome but neither work and -or give me a "can we use your microphone" dialog.

Any fix for this?

**Comment by TalAter** [comment]
annyang relies on the browser to do the speech recognition. Unfortunately, Apple chose not to adopt speech recognition, along with many, *many*, other modern web features in Safari. 

Also unfortunate, is that iPhones do not allow true 3rd party browsers... so even Chrome on an iPhone is just Safari's engine (WebKit) with a Chrome like wrapper around it.

So, yeah... even the newest browser on the latest most expensive iPhone is no match for Chrome or Opera running on an old Android phone... at least when it comes to supporting web standards.

This is why so many people are calling Safari the new IE.
