### ISSUE TITLE
addCommand callbacks should be invoked after addCallback callbacks

### ISSUE THREAD

**Issue by ngryman** [TalAter/annyang#247]
I would like to display the recognized text before executing the command callback and display the processed answer. With the current implementation it's difficult.

## Expected Behavior

From my point of view, `addCallback` callbacks are generic ways of reacting to your library and should be called before any processing your side.
A nice side effect would be, in my case, to be able to display raw informations (like what the user said), before any further processing.

## Current Behavior

`addCommand` callbacks get invoked before `addCallback` callbacks. 

## Possible Solution

I guess it would be a trivial change, just swap the order of calls.

## Steps to Reproduce (for bugs)

```js
annyang.addCallback('resultMatch', () => {
  console.log('callback')
})

annyang.addCommands({
  'command': () => console.log('command'),
})

// command
// callback
```

## Context

I'm trying to develop a dialog style resume. I would like some sort of live transcript being displayed.

## Your Environment

* Version used: `2.6.0`
* Browser Name and version: `Chrome Version 55.0.2883.95 (64-bit)`
* Operating System and version (desktop or mobile): `macOS Sierra 10.12.1`
* Link to your project: `n/a`

**Comment by TalAter** [comment]
Hi @ngryman 

I can see your point of view of having that execution order over the current one. But I can also imagine others already depending on the current order in their code... to them changing the current order might be a breaking change.

I don't think this would be enough of a benefit for most people to warrant a breaking change in the API.

**Comment by ngryman** [comment]
Ok I understand that. What about introducing a new callback for that specific purpose?
