### ISSUE TITLE
Annyang in Electron Speech Recognition is repeatedly stopping and starting

### ISSUE THREAD

**Issue by ialberquilla** [TalAter/annyang#248]
I'm using an example app created in Electron, donwloaded from:
https://github.com/TalAter/annyang-electron-demo

But when I start it in debug mode, it shows in the console:
Speech Recognition is repeatedly stopping and starting. See http://is.gd/annyang_restarts for tips.

I'm not using Speech Recognition in any other tab.

I'm using this versions:

node 5.1.1, Chromium 47.0.2526.110, Electron 0.36.12, and annyang.

Any idea?

Thanks!

**Comment by jchook** [comment]
I'm also having a similar issue. Attempting to create a website to initiate timers by voice command. As I switch between apps, etc the availability of the voice recognition is highly unpredictable.

**Comment by TalAter** [comment]
I believe this might be related to the API limits on Electron. See https://github.com/TalAter/annyang/blob/master/docs/FAQ.md#can-annyang-be-used-in-chromium-or-electron
