### ISSUE TITLE
Stop when there is sound but no words

### ISSUE THREAD

**Issue by Nixellion** [TalAter/annyang#249]
I may be wrong, but right now it seems that Annyang only tracks it when there is no sound anymore to stop the recognition and return the result.

I think it would be nice if it could stop recording if there is sound, but no words recognized for a second or two.

This would allow it to work better in loud environments. Right now if there is some loud sound in the background, like music without words or any other noise - it keeps recording until that sound is killed.

**Comment by jchook** [comment]
Sounds like this would require "word recognition" software in front of the browser API. This bug should be reported to Google Chrome, no?

**Comment by TalAter** [comment]
Yes, the implementation of the recognition is up to the browser vendor.
