### ISSUE TITLE
One phrase to trigger two commands. 

### ISSUE THREAD

**Issue by BetaStacks** [TalAter/annyang#251]
Any thoughts on how to trigger two commands with one phrase?

## Desired Behavior
I would like to setup two separate commands such as "Turn on all lights." and "Play music." and then have them both triggered with the phrase "Turn on all lights and play music". 

## Current Behavior
Right now I have to create a separate command that will trigger both commands. This is fine if there are only or two combinations but gets extremely tedious if you have several dozen combinations.  

## Possible Solution
Perhaps there is a way to parse commands. I'm not really sure what a good solution could be at the moment.

**Comment by PortPixel** [comment]
Perhaps in each command check the whole speech said for 'and' and then parse the text after 'and' to check for another command?

**Comment by popbijoux** [comment]
I know what you mean @BetaStacks this reminded me of a question I had and found the answer (in my case, I wondered how could I use a single command in several languages.  I would think your best bet would be an answer similar to the one given about the languages (see below, link to full question "How to specify multiple languages": https://github.com/TalAter/annyang/issues/119). 

In other words, you're better off defining one given function and then adding the commands as they grow.  Annyang WILL pick up both commands from the same phrase if you define the terms separately, (I have tested it on my own application and it worked). See the original answer screenshot: 
![screen shot 2017-03-27 at 3 21 36 pm](https://cloud.githubusercontent.com/assets/21673735/24374267/2dd69e32-1302-11e7-8c38-36cec441ee44.png)

https://github.com/TalAter/annyang/issues/119

**Comment by TalAter** [comment]
> The issue you are describing is something I feel I will also run into in the future with scaling and it's best dealt with via NLP algorithms. But that adds a different layer of complexity that is perhaps unnecessary, so unless you're building a 100% voice interface, using nlp might be too much of an investment, and annyang is really meant for simplicity, I think.

💯 👍 
Well said.
