### ISSUE TITLE
Is it possible to initiate multiple instances of annyang at the same time?

### ISSUE THREAD

**Issue by krahnemoon** [TalAter/annyang#255]
The title explains it all.
If it isn't, it could be a great feature to add.
For example, the first instance could consist of one listener such as "Hey Assistant"
and once the listener is triggered the rest of the commands initiate with another instance of annyang.

**Comment by jdChum** [comment]
Multiple instances would cause trouble with the underlying APIs that Annyang provides an interface for. This is one of the reasons why having listeners in multiple tabs cause Annyang to start and stop repeatedly. Instead, you could use a single command as a wake word or phrase that adds a library of other commands.

`let commands = {
  'google *query': query => { searchGoogle(query); },
  'how\'s the weather in *location': location => { getWeather(location); }
}

let wake = {
  'hey assistant': () => {
    annyang.addCommands(commands);
    // remove commands after 2 seconds of inactivity
    setTimeout( () => {
      annyang.removeCommands(Object.keys(commands));
    }, 2000);`

If you go with this technique, you'll need to remove the commands after each command routine runs. That way, the speaker has to use the wake phrase before using any commands every time.

**Comment by jdChum** [comment]
Multiple instances would cause trouble with the underlying APIs that Annyang provides an interface for. This is one of the reasons why having listeners in multiple tabs cause Annyang to start and stop repeatedly. Instead, you could use a single command as a wake word or phrase that adds a library of other commands.

```javascript
let commands = {
  'google *query': query => { searchGoogle(query); },
  'how\'s the weather in *location': location => { getWeather(location); }
}

let wake = {
  'hey assistant': () => {
    annyang.addCommands(commands);
    // remove commands after 2 seconds of inactivity
    setTimeout( () => {
      annyang.removeCommands(Object.keys(commands));
    }, 2000);
```

If you go with this technique, you'll need to remove the commands after each command routine runs. That way, the speaker has to use the wake phrase before using any commands every time.
