### ISSUE TITLE
Annyang in Chromium: keeps stopping and starting

### ISSUE THREAD

**Issue by hakhag** [TalAter/annyang#257]
Hello!

So I'm trying to add annyang to a node.js app I'm running in the Cromium browser. Everything works fine in Chrome, but in Chromium I'm having some issues. Annyang tells me it keeps stopping and starting:

`Speech Recognition is repeatedly stopping and starting. See http://is.gd/annyang_restarts for tips.`

I know this can be caused with having multiple tabs/windows running annyang open, but I only have one active.

I have created the Google keys (https://www.chromium.org/developers/how-tos/api-keys) and placed them in my `.bash_profile`. However, I'm still getting this message and I'm suspecting I've done something wrong with the keys. Exactly where should I place them, and do I need to take any special steps in order for them to work? I'm on Mac OSX. Should also note that the `printenv` command in the terminal returns the right keys.

And for the record: I've tried running my localhost server on HTTPS with a Self Signed Sertificate also, but to no avail.

Thanks!

**Comment by sdawson26** [comment]
I've dealt with this issue before as well. You need to use these parameters to get it to stop:
annyang.start({autoRestart:false, continuous: false});

**Comment by hakhag** [comment]
@sdawson26 thanks for reply. I've tried this, but it only results in annyang stopping right away (the `recognition.onend` is triggered almost immediately). Then the `recognition.onstart` is triggered a second later, and `recognition.onend` is triggered again right after. This goes on forever.

**Comment by hakhag** [comment]
Right, so after alot of hairpulling why this didn't work I've figured it out. It came down to two errors I had made:

1. I had enabled the "Google Cloud Speech API" and not the "Speech API". Apparantly these are two different things.
2. I had to launch Chromium in the terminal with the command `/Applications/Chromium.app/Contents/MacOS/Chromium` so that it would registert the API keys.
