### ISSUE TITLE
Can I force the annyang to parse string word number to actually integer numbers?

### ISSUE THREAD

**Issue by sayeko** [TalAter/annyang#258]
Hey, I would like to know if there is some way to force annyang to parse word numbers.

for example: five hundred to 500.

currently it sometime gives me 500 and five hundred.

## Expected Behavior
Speaking to mic asking for five hundred
expected to return `500` and not five hundred.

## Current Behavior
Sometime return 500 and sometimes return five hundred as word string.

**Comment by sdawson26** [comment]
I've had the same problem before and unfortunately this is something that cannot be avoided. Something like this should do the trick:

http://stackoverflow.com/questions/11980087/javascript-words-to-numbers

**Comment by oshihirii** [comment]
For another reference, I have come across:

https://github.com/howlowck/words-to-num

And asked if this is a valid implementation in plain javascript:

https://github.com/howlowck/words-to-num/issues/1

There is a working jsFiddle link there.

**Comment by TalAter** [comment]
There isn't a way to force the speech to text engine to return numbers as a numerical representation or as words.

Your best bet would be to parse the results as suggested by @sdawson26 and @oshihirii.
