### ISSUE TITLE
Can the end-user click a button to wrap-up or "finish listening" rather than pausing or aborting?

### ISSUE THREAD

**Issue by sdawson26** [TalAter/annyang#259]
## Expected Behavior
Impatient users want something to click when they are done talking rather than waiting for the speech recognition to stop on its own.

## Current Behavior
Right now we can only use pause() to momentarily pause (still leaves the microphone on) and abort() which cancels out the command entirely.

## Possible Solution
I would like something like ... `annyang.stopListening()` so that the user can expedite the callback.

## Steps to Reproduce (for bugs)
N/A

## Context
I've demoed Annyang to a few of the end users of my application and some of them are confused about "waiting for the speech recognition to stop listening". Some of them expect the microphone button to toggle beginning/ending a command. Instead, I can only build the button to begin/abort, so when they click it a second time and "nothing happens", they report it to me as a "bug".

Some of them are used to Siri/Alexa/Google commands so I'm trying to make this behave like other tech they already understand. However, when you are done talking to Siri, clicking the same button you began your command with does not abort the command. Instead, it tells Siri that you're done talking and ready for her response.

## Your Environment
Chrome, MacOS. Trying to roll it into a mobile app as well but, so far, unsuccessful.

**Comment by TalAter** [comment]
Unfortunately this isn't possible. It is up to the browser when to send the speech to the server to be parsed... annyang can't change that.
