### ISSUE TITLE
Prepared for multiple word options

### ISSUE THREAD

**Issue by Iazzetta** [TalAter/annyang#261]
I want to make a commands like this?
```
"you are (super|big) :adjctive": function(adjective){
        console.log(adjective);
 },
```
Can I? I try using " | " but don't work.
Thanks btw

**Comment by TalAter** [comment]
You can do by defining your commands as regular expressions. This is explained in the [API docs](https://github.com/TalAter/annyang/blob/master/docs/README.md#using-regular-expressions-in-commands).

**Comment by Iazzetta** [comment]
Thanks! This solve my problem.
