### ISSUE TITLE
Annyang not working Chrome/Ubuntu

### ISSUE THREAD

**Issue by Iazzetta** [TalAter/annyang#262]
I create some project with Annyang using osx (Works just in Chrome Canary).
Now, I trying use linux and not work! Don't detect my audio. I try in annyang website to test and not work too.

Google Chrome version: 57.0.2987.98 (Official Build) (64-bit)
Ubuntu.

**Comment by Stas-Buzunko** [comment]
It has been working on my ubuntu / Chrome for something like month, but today it stopped working.
Don't even know how to debug it.
Chrome Version 55.0.2883.87 (64-bit)

**Comment by popbijoux** [comment]
Hey @Stas-Buzunko I have had something like this happen to me, and I saw that I was using their external link , I went ahead,  downloaded the annyang js file and inserted onto my folder and linked the html to it and it worked after that. I

**Comment by Iazzetta** [comment]
@popbijoux oh maybe you're right. I'm using CDN...

**Comment by popbijoux** [comment]
@Iazzetta I have had several issues with annyang configuration and this was one thing that worked for this one problem. The second issue I have run into was that my computer that was not picking up  audio at all and third issue is code error on my end, because I use annyang to trigger show/hide divs and that's another issue altogether:)

**Comment by Stas-Buzunko** [comment]
@popbijoux thank you! i've been using cdn as well. Going to try to download today!

**Comment by Stas-Buzunko** [comment]
i've tried local file, it didn't work
But it suddenly started working when I added annyang.debug() in the beginning :)

So my recommendation to try to call debug if nothing above helps. +it's funny to see how it recognizes speech in console
