### ISSUE TITLE
Portuguese - Brazil

### ISSUE THREAD

**Issue by GlauberF** [TalAter/annyang#263]
## doubt
I'm trying to use it on my site, but I did tests with it and set the Portuguese language, but I did not recognize it, do you have any examples for me to see or how can I do it, if it's portuguese brazil?

**Comment by TalAter** [comment]
Portuguese (Brasil) is on the [list of supported languages](https://github.com/TalAter/annyang/blob/master/docs/FAQ.md#what-languages-are-supported)

Did you try [setting the language](https://github.com/TalAter/annyang/tree/master/docs#setlanguagelanguage)?

````javascript
````

**Comment by GlauberF** [comment]
I'll test, then tell me more if it worked

Example command, if I want to edit a product, I'll speak edit product x, x is the product id, how could I mount this, pass that command?
