### ISSUE TITLE
I m getting below error while doing -npm install 

### ISSUE THREAD

**Issue by gauravmishra123** [TalAter/annyang#264]
while doing -npm install I am getting belown error .

Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt

## Steps to Reproduce (for bugs)

1.Forked the repository with my username
2.Did cloning using the command given in the CONTRIBUTING.md
3.After that , as suggested in this document ,i did -npm install and it is throwig the below error
4.Due to which the grunt command is also not working

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by TalAter** [comment]
I am sorry, but this seems to be a local error (perhaps with your installation of node or npm)... not something I can help debug.
