### ISSUE TITLE
Make it recognise faster?

### ISSUE THREAD

**Issue by theonlygusti** [TalAter/annyang#265]
I only have a lot of short, single-word commands, like "one", "two", ... "nine."

I have to pause for a few seconds for each one to be recognised.

Add a config option to make this faster?

**Comment by TalAter** [comment]
Unfortunately that is up to the speech recognition engine in the browser, not annyang. Here are a few tips on how to get [faster speech recognition results](https://github.com/TalAter/annyang/blob/master/docs/FAQ.md#what-can-i-do-to-make-speech-recognition-results-return-faster).
