### ISSUE TITLE
Regex with splats

### ISSUE THREAD

**Issue by Waynewil** [TalAter/annyang#266]
How do I use regex with splats?

This works for the first word in the splat:

'add *specifiers': {'regexp': /^(?:add|at|and) (\w*)$/, 'callback': addFunction}

...but I'm unable to find how to capture the entire splat. The fault here is entirely mine, i.e. I'm new to regexp. But after hours of reading/hacking, the correct expression eludes me.

Thanks,

Wayne

**Comment by TalAter** [comment]
Can you explain a bit more what you are trying to accomplish with the regular expression? Maybe someone here will be able to help with it.
