### ISSUE TITLE
Annyang is simply not working

### ISSUE THREAD

**Issue by AdRiAnIlloO** [TalAter/annyang#267]
Hi,

I followed the first example listed on the web to handle a command. I did that on my webserver and it isn't working: means, the callback isn't getting called (I ensured it by getting empty output after a logging, anyways my custom code wasn't being executed, despite not having pasted it here). The web uses HTTPS already due to a requirement by another library, and the mic has permissions:

`voiceCommands = {
    'ping': function() {
        // code for my project
    }
}

if(annyang) {
    annyang.addCommands(voiceCommands)
    annyang.start()
}`

Note: I also tried with "hello" command, it didn't work aswell.

Also, I made a simple log to check if the present "annyang" condition is entered, thus being initialized, and it is. I can speak the examples from the annyang web and it works without problem.
What could it be? Am I doing something wrong?

Many thanks.

**Comment by peterdillon** [comment]
Have you made a fiddle or pen to troubleshoot?

**Comment by AdRiAnIlloO** [comment]
https://jsfiddle.net/qagzxnvs/

**Comment by popbijoux** [comment]
the only thing that REALLY worked for me was hosting the page on a github page. Getting HTTPS permission on your computer is not enough, you need to host it on a localhost (via python/terminal, I'm on a MAC) or just host it elsewhere.  I ran into this problem before with d3 where I also had to host it on github or it would not appear on the browser, I don't like doing localhost if I am working on it all the time.

**Comment by AdRiAnIlloO** [comment]
It turns out that the speech recognition has many difficulty to hear for some short words. Regarding 'hello', I was just not saying it loud enough (I'm using a webcam mic which I need to keep using instead of a headset, since I'm doing an interactive camera+mic pong game, and player should be able to play it being a bit away from screen, so having to use a headset would be annoying).

The case is, I need at least the word 'ping' to be handled in my minigame web, and it isn't being recognized. Is there anything to do here, like maybe some annyang functions to maximize hearing of short words like this?

https://jsfiddle.net/qagzxnvs/9/

Here you can check what I mean. Delete the 'es-ES' language setting, but you should have the same problem. Instead, it seems the speech recognition works well saying loud phrases.

**Comment by TalAter** [comment]
It seems that annyang is working correctly here... the only issue is that Google's speech recognition engine incorrectly identifies these two words, as they are not very common (not many people just say "ping" as a sentence, so the Speech Recognition engine assumes it must be something else). You correctly identified that when you say a longer sentence it does work, as you are providing the Speech Recognition engine with some context, so it finds it easier to correctly recognize what you are saying.

The only possible solution I can offer is to try different keywords, or phrases... the rest is out of annyang's hands.

**Comment by kylebakerio** [comment]
Just wanted to mention that, since it seems annyang returns an array of things you may have possibly said, you could sort through those results and hunt for any indication that 'ping' is present in any possible interpretations, to select for that interpretation more aggressively. (Perhaps this feature was not available in 2017, and I'm suggesting this only after a first reading of the docs myself.)
