### ISSUE TITLE
Great Script!!! How to add a FIXED VARIABLE as part of the VOICE COMMAND

### ISSUE THREAD

**Issue by inglesuniversal** [TalAter/annyang#272]
I have this simple issue, but can't figure out how to fix it...

your script has this to insert variables into the VOICE COMMAND...

  // A named variable is a one word variable, that can fit anywhere in your command.
  // e.g. saying "calculate October stats" will call calculateStats('October');
  'calculate :month stats': calculateStats,

in the scenario above the variable is :month 

My question is HOW to insert a fixed variable into the VOICE COMMAND...

`        ':VAname do you like ice cream': function(VAname) {      `

I am trying to insert a Virtual Assistant NAME previously picked by the USER, but so far, ANY name spoken into the microphone can be used to trigger the command.... 

HOW can I make it UNIQUE?

Thanks

Hugo

**Comment by TalAter** [comment]
You can write a function that will be called every time you change the assistant name and will remove all the commands, and register new ones instead. These new commands will have the assistant name hardcoded in them.

For example:
````javascript
var registerNewVA = function(name) {
  var newCommands = {};
  newCommands[name+' turn :state the lights'] = function() {};
  newCommands[name+' wake me up in :number minutes'] = function() {};
  annyang.removeCommands();
  annyang.addCommands(newCommands);
};
registerNewVA('eva');
````

You can read more about [addCommands](https://github.com/TalAter/annyang/blob/master/docs/README.md#addcommandscommands) and [removeCommands](https://github.com/TalAter/annyang/blob/master/docs/README.md#removecommandscommandstoremove) in the docs.
