### ISSUE TITLE
Command to HALT all actions even if audio / music is being played back...

### ISSUE THREAD

**Issue by inglesuniversal** [TalAter/annyang#276]
Hello:

Is there a way to have a VOICE command that can be used to stop playback of long TTS narration as well as music being played and triggered by a previous voice command?

Something like... "Virtual Assistant's Name" STOP!!!!

I have tried some combinations either through the internal mike on my mac or the audio being played on my apple tv and NO good results to report.

**Comment by TalAter** [comment]
The specifics of how you stop the narration or music are up to your program, not annyang.

Just create a function that stops the narration or music (for example `stopPlaying()`) and then call it from an annyang command like so:

````javascript
annyang.addCommands({
  'stop immediately': stopPlaying
});
````
