### ISSUE TITLE
PhantomJS timed out, possibly due to an unfinished async spec.

### ISSUE THREAD

**Issue by Kacppian** [TalAter/annyang#277]
I didn't make any changes to the files, I just cloned the repo and tried running grunt.

When I try running grunt dev I get this output - 

>> ReferenceError: Can't find variable: require at
>> test/SpecRunner.html:34 global code
>> ReferenceError: Can't find variable: require at
>> test/SpecRunner.html:50 global code
>> ReferenceError: Can't find variable: require at
>> test/SpecRunner.html:62 launchTest

and it aborts. I did try using --force but nothing happens beyond the error. 

## Your Environment

* Version used:  node Version - v6.3.1, npm Version - 4.5.0
* Browser Name and version: Google Chrome
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by TalAter** [comment]
Hey @Kacppian 

The latest update I just made should hopefully resolve this.

Could you please test it out and let me know? Thank you.
