### ISSUE TITLE
What is returned on resultNoMatch?  

### ISSUE THREAD

**Issue by oshihirii** [TalAter/annyang#284]
I am reading this documentation:

https://github.com/TalAter/annyang/blob/master/docs/README.md#addcallbacktype-callback-context

It gives a good example of exactly what is returned from `resultMatch`:

```
annyang.addCallback('resultMatch', function(userSaid, commandText, phrases) {
  console.log(userSaid); // sample output: 'hello'
  console.log(commandText); // sample output: 'hello (there)'
  console.log(phrases); // sample output: ['hello', 'halo', 'yellow', 'polo', 'hello kitty']
});
```

What exactly is returned from `resultNoMatch`?

I have read this sentence:

> `resultNoMatch` - Fired when what the user said didn't match any of the registered commands. Callback functions for this event will be called with an array of possible phrases the user might've said as the first argument

So does that mean it only returns `phrases`, or is other data returned?  

In either case, a full code example of `resultNoMatch` would be much appreciated.

Thank You!

**Comment by oshihirii** [comment]
As a follow up, I tried:

```
annyang.addCallback('resultNoMatch', function(possible_phrases) {
console.log(possible_phrases);
});
```

and yes it seems to just return possible phrases (i'm not sure if it returns other things though).

**Comment by TalAter** [comment]
It only returns the phrases.

You can test this out yourself by running:
````javascript
annyang.addCallback('resultNoMatch', function(arguments) {
  console.log(arguments);
});
````
