### ISSUE TITLE
Node Microphone Stream with Annyang Node

### ISSUE THREAD

**Issue by BetaStacks** [TalAter/annyang#287]
Would this [Microphone-Stream](https://www.npmjs.com/package/microphone-stream) work with the Node version of Annyang?

If so then this may be a way to get around the beeping on mobile.

**Comment by TalAter** [comment]
No. annyang was not built to work with any other APIs except the browser's speech recognition.

**Comment by vin-ni** [comment]
I built a node speech rec with a stream to work everywhere: https://github.com/vin-ni/Google-Cloud-Speech-Node-Socket-Playground
