### ISSUE TITLE
Can I install annyang using npm and webpack?

### ISSUE THREAD

**Issue by HeinPauwelyn** [TalAter/annyang#290]
## Expected Behavior

using next command to use Annyang in my application:

```shell
npm install annyang --save
```

and add using it inside my JavaScript code like this using webpack:

```js
var annyang = require('annyang');
```

## Current Behavior

You need to add this html code:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/annyang/2.6.0/annyang.min.js"></script>
```

## Possible Solution

Several things to do that. [See also this link.](https://docs.npmjs.com/getting-started/publishing-npm-packages)

## Context

Minify all code inside one JavaScript file named `bundle.min.js`.

**Comment by MiHawkStackOverFlow** [comment]
Can I take this up ? I am a beginner on github. Let me know whatI  need to do ? is minification needed for js files ?

**Comment by germanamz** [comment]
the npm module is on [https://www.npmjs.com/package/annyang](https://www.npmjs.com/package/annyang)

**Comment by codevenkat** [comment]
@germanamz but I can only use 'import' commands? I am not sure if I can use `require()`(node)

**Comment by alexcastillo** [comment]
Try `import * as annyang from 'annyang';`.

**Comment by K3nnythe13ed** [comment]
tried to import it that way, but i always get:
[ts] Property 'addCommand' does not exist on type 'typeof "node_modules/@types/annyang/index"'.

**Comment by dpschen** [comment]
You can import with the help of the [exports-loader](https://github.com/webpack-contrib/exports-loader) like this:

```js
import annyang from 'exports-loader?annyang!annyang';
```

or

```js
const annyang = require('exports-loader?annyang!annyang');
```
