### ISSUE TITLE
Android Webview - Annyang does it work

### ISSUE THREAD

**Issue by ardakazanci** [TalAter/annyang#292]
Hi, can I do this.
What are the alternative ways.

**Comment by BetaStacks** [comment]
I would imagine that if it works you would still get the beeping every couple seconds when the mic is being used.

**Comment by HannesOberreiter** [comment]
It does not work so far, the Webview seems to not support the speech API.

**Comment by macdonst** [comment]
@ardakazanci my speech rec plugin for Apache Cordova apps would let you use Annyang inside an Android WebView. https://github.com/macdonst/SpeechRecognitionPlugin
