### ISSUE TITLE
How can I *display the text of what the user said, just as it was said, regardless of whether it's a command match or not? 

### ISSUE THREAD

**Issue by popbijoux** [TalAter/annyang#294]
hi, thank you so much re: [the last issue #293 ](https://github.com/TalAter/annyang/issues/293).  I was not able to re-open it so I am posting it as a new issue. 

I managed to make the text show on a div, BUT the text is displayed in an array, as explained on your FAQ:[ "_[This event will fire with a list of possible phrases the user may have said, regardless of whether any of them matched an annyang command or not.](https://github.com/TalAter/annyang/blob/master/docs/FAQ.md#can-annyang-be-used-to-capture-the-full-text-spoken-by-the-user)_"

This is the code:

```
annyang.addCallback('result',function(whatWasHeard) {
document.getElementById("voiceToText").innerHTML = whatWasHeard;
});
```
It displays both the actual matched command and other possible phrases.  
**Is there a way to display everything the user said, NOT in an array, regardless of whether it is a match or not?**

For example if I say the word "toast", 
I get _first, toast, 1st, post_

When I say _I had toast for breakfast_ I get 
_ask for breakfast, can I ask for breakfast, contact for breakfast_ as a result.
which is not what I said:(

**All I want is, if I say _I had toast for breakfast_
I get exactly the same as a result: _I had toast for breakfast_**

I tried using splats and such but it did not work for me:(

Thank you again!

**Comment by TalAter** [comment]
Answering in the original issue. there is no need for a separate one.
