### ISSUE TITLE
Allow OR in rules

### ISSUE THREAD

**Issue by TalAter** [TalAter/annyang#30]
e.g.
````````````
  var commands = {
    'show||display tps report': function() { $('#tpsreport').show(); }
  };
````````````

**Comment by alanjames1987** [comment]
+1

**Comment by BoKu** [comment]
+1

**Comment by TalAter** [comment]
Version 2.0.0 released yesterday supports regular expressions which should allow for all the cases described above.
@BoKu , @alanjames1987 , @Glavin001 , @gitnik  - I would love your feedback on the new feature - https://github.com/TalAter/annyang/releases/tag/v2.0.0

**Comment by Glavin001** [comment]
Awesome, regex support is great! Thanks!

**Comment by alanjames1987** [comment]
@TalAter That is a great way to add these and many more features. Thank you.

**Comment by TalAter** [comment]
:+1: Awesome.
