### ISSUE TITLE
Firefox Supports Speech Api since 49

### ISSUE THREAD

**Issue by vin-ni** [TalAter/annyang#308]
Is it possible to add firefox support to Annyang?

[Mozilla](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API) says that it is supported since v49 and the [google speech demo](https://cloud.google.com/speech/) works on my current firefox (55).

**Comment by SammyIsra** [comment]
If this is still active, I could tackle this!

**Comment by TalAter** [comment]
@SammyIsra Go for it! Thank you ✊

**Comment by SammyIsra** [comment]
Hey! I'm running into a bit of an error. When trying to run in dev, I am getting the following error:
![image](https://user-images.githubusercontent.com/8962228/34322836-901f30e4-e800-11e7-9bc2-148a65aeb4d9.png)
And when I checked, the minified file only has this: 
![image](https://user-images.githubusercontent.com/8962228/34322848-c7fd6a6c-e800-11e7-9b1e-5f690be678a4.png)
Any idea why this would be? I'm working on a Windows machine, if that matters

**Comment by SammyIsra** [comment]
Additionally, I wanted to ask something about the SpeechRecognition API. 

Also, only part of the Web Speech API is supported on Firefox. This [table compatibility table on MDN shows](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition#Browser_compatibility) that SpeechRecognition is still not supported on anything but Chrome, but it is planned for at least Mozilla.

One of the footnotes on the Web Speech API says:
>Note that currently only the speech synthesis part is available in Firefox Desktop — the speech recognition part will be available soon, once the required internal permissions are sorted out.

If we use the Google Speech demo, we are no longer in the realm of the browser. We'd need to make requests to Google services, which do [have a price](https://cloud.google.com/speech/#cloud-speech-api-pricing)

Personally, I would hold off on this until the SpeechRecognition API is available on Mozilla.

What do y'all think?

**Comment by vin-ni** [comment]
Yeah, it's what I thought :/
Thank you so much! :)

**Comment by TalAter** [comment]
Yes, as @SammyIsra writes, only the speech synthesis is available in Firefox (and a few other browsers). Native speech recognition is still only available in Chrome.

The demo you pointed out in the first issue does not use the Speech Recognition spec but a proprietary paid solution offered by Google.

Closing this for now as @SammyIsra suggests
