### ISSUE TITLE
Is there a parameter that specifies the speed of speech?

### ISSUE THREAD

**Issue by popbijoux** [TalAter/annyang#315]
Project overview/Context
Hi I have been using Annyang for a project that turns speech into continuous animation and one of the elements I am working on is connecting voice to character speech. Meaning an image of a character would show she/he speaking whatever the user said. In addition to that, the content of speech, and the speed of the speech, would show a story appearing continuously that illustrates what the user is saying, once voice recognition turns voice into text.

Specific issue within project:
In animation there are mouth shapes specific to some words and syllables which is not directly related to voice recognition or annyang itself (I am creating a set of JS algorithms that will process text and connect to to image assets after the voice is recognized by Annyang). 

However there is one parameter that is important and that is the speed of the speech itself.  This isn't super crucial, I can create a "standard" speed for the characters, and since what I am working on is more on the cartoon than "realistic", it doesn't have to be super precise, but it should feel like it's not moving randomly, that there should be some connection to the speed of the voice. I am assuming this might be done by calculating the speed in which the text is written into the text input box, but ideally, if there is a speed parameter in place it could be helpful.

**Comment by TalAter** [comment]
Very interesting use case. I would love to see it when you have something ready.

Regarding your specific issue. Unfortunately, there isn't anything in the Web Speech API specification, or any of the browser implementations I know that supports that... and so, neither does annyang.
