### ISSUE TITLE
Possible to show debugging links on annyang web page?

### ISSUE THREAD

**Issue by darren-a** [TalAter/annyang#316]
I'm currently debugging my system to find out why speech recognition is not working* and it's not the annyang web page at fault - nevertheless would it be possible to include some general debugging links on the page for those who are new to working with speech recognition in the browser?

Also if the page could give some feedback to the extent that speech (or sound, at least) has been detected that would be helpful (maybe it does and I'm not noticing it).

*(Chrome 61 on OS X El Capitan, internal mic works fine, web page is allowed mic user, tab shows red recording icon, same symptoms on davidwalsh.name and google search)

**Comment by darren-a** [comment]
Some links:

https://www.google.com/intl/en/chrome/demos/speech.html
https://www.textfromtospeech.com/en/voice-to-text/

Apparently the "(latest version of Chrome does support it)" (ie. speech recognition), according to textfromspeech website, though they don't give a time reference on this.

**Comment by darren-a** [comment]
I updated to Chrome 62 and it's working (though afaik it should've worked ok in 61)

links:

https://support.google.com/chrome/answer/95414?co=GENIE.Platform%3DDesktop&hl=en
https://www.google.com/intl/en/chrome/demos/speech.html
https://cloud.google.com/speech/

**Comment by TalAter** [comment]
You can call `annyang.debug()` to turn on detailed debug messages. This is explained in the [api docs](https://github.com/TalAter/annyang/blob/master/docs/README.md#debugnewstatetrue).
