### ISSUE TITLE
Workaround for use of annyang with electron?

### ISSUE THREAD

**Issue by qnoox** [TalAter/annyang#317]
Hello,

First of all thanks for reading and annyang is great.

So i have have looked at closed/open issues and forums etc and i found out that electron and annyang is not valid anymore due to some changes in the speech module.

My question is: "i feel as the question just faded and closed down i would like to continue the search for a possible solution". if you don't mind at least provide with some possible ways to look into it even it's a horrible workaround i would like to know about it if you would be so kind.

Thanks in advance & have a great continued day.

## Expected Behavior
in theory it should work.

## Current Behavior

i get the same as reported before network error.. as others have got.

## Possible Solution

here is where i need assistance if possible.

## Steps to Reproduce (for bugs)

1. tested annyang electron + my own setup
2. both end up with network error.

## Context

trying to build a simple voice to command for an desktop app.

**Comment by TalAter** [comment]
Some community members have suggested this: https://github.com/TalAter/annyang/blob/master/docs/FAQ.md#can-annyang-be-used-in-chromium-or-electron

Does this help? If not, feel free to reopen the issue
