### ISSUE TITLE
arabic not working

### ISSUE THREAD

**Issue by ADAMSANI** [TalAter/annyang#318]
how to use Arabic text , I tried to type in Arabic and also I tried to type Arabic text in English letters but both not working

**Comment by TalAter** [comment]
What do you mean tried to type? Do you mean in your code editor when you defined the commands?

It should work, I've tried it myself. If it doesn't there may be a problem with how your code editor saves the files in languages other than English. That is something worth checking.

Also, make sure you've set the language as explained [here](https://github.com/TalAter/annyang/blob/master/docs/README.md#setlanguagelanguage)

**Comment by ADAMSANI** [comment]
im sorry but can you share the code you have test arabic with 
its not working with me

**Comment by TalAter** [comment]
I don't have it anymore.

Can you share the code you've used, and I'll be happy to go over it

Tal Ater

**Comment by ADAMSANI** [comment]
thanks alot it works !!
there was an error in the order of the codes .. I'm very thankful for you

**Comment by TalAter** [comment]
Great to hear that 🎉
