### ISSUE TITLE
Recognize words from 2 different languages at the same time

### ISSUE THREAD

**Issue by nirsharony** [TalAter/annyang#319]
Hi,

I am using the library to recognize speech which can come in various languages.
The set of words that I need to recognize can be either in English or in some other language.
This means that while 90% of the words will be in Spanish (for example), 10% of the words might be in English.

I know that the library can be configured with the language code using the setLanguage method.
However, if I set the value to be es-ES, how can I detect the remaining 10% of the words which will be in English?

Is there a workaround to get this done?

Thanks,
Nir

**Comment by TalAter** [comment]
Hi Nir,

annyang does not do the actual speech recognition itself. Instead, it serves as a layer on top of the speech recognition engine that is built into the browser. Unfortunately defining multiple languages isn't supported by the speech recognition APIs exposed by the browser, or the spec defined by the W3C.
