### ISSUE TITLE
My microphone remains disabled on my web page

### ISSUE THREAD

**Issue by MrDu91** [TalAter/annyang#320]
Hello everyone,

I started a small project with the use of Annyang, but I have a problem with the activation of my microphone. When I use my program in localhost, it works very well, but once I put it online on my site, my microphone remains in "Continue to block access to the microphone" mode.

I tried to allow my microphone by changing the settings of my microphone in Google chrome but still the same result my microphone remains blocked on my web page and it is impossible to allow it because it always come back in the mode "Continue to block access to the microphone ".

So my question is: Do I have to put something in the code so that my microphone is activated? or maybe we have to do something else but I do not see what.

Hoping that you will understand my problem, thank you in advance for your answers.

**Comment by sbs0034** [comment]
I am getting 
```
SpeechRecognitionError {isTrusted: true, error: "not-allowed", message: "", type: "error", target: SpeechRecognition, …}
```
when I try to access it from another computer. Localhost works just fine, and phone browser works just fine.

**Comment by TalAter** [comment]
Is your site hosted on HTTPS? It seems like the Chrome team has recently hardened the requirements for Speech Recognition (and other things) to require HTTPS.

**Comment by MrDu91** [comment]
My site is hosted on http and not on https.

**Comment by TalAter** [comment]
That is probably the reason then.

Many of the newer browser APIs only work on HTTPS, and some of the ones that used to work on HTTP (e.g., geolocation) have been changed to only work on HTTPS.

It might be worth making the move.

**Comment by MrDu91** [comment]
Thank you for your reply and your informations! I take note and I will make the change! Thank you ! :)

**Comment by droidriz** [comment]
This helped me opening it with https worked.
