### ISSUE TITLE
annyang works well on my desktop browser, but on on chrome browser when wrapped in a phonegap build app

### ISSUE THREAD

**Issue by nirsharony** [TalAter/annyang#321]
Hi,

When embedding the annyang object and using it on my phonegap build app on Android, I don't get any request by the phone giving it permission to use the microphone. 
When the app was first tested on my desktop browser, I got the permission dialogue.

This means that I am unable to test the integration with annyang on my Android device.
I did install the following plugins:
- cordova-plugin-crosswalk-webview
- cordova-plugin-crosswalk-webview
Is there anything else that I need to do?

**Comment by macdonst** [comment]
@nirsharony the webview on Android does not support the web speech api and AFAIK neither does crosswalk. You can try adding https://github.com/macdonst/SpeechRecognitionPlugin to your project but I haven't had a chance to mess with in in awhile.
