### ISSUE TITLE
Using natural speech with annyang?

### ISSUE THREAD

**Issue by Senshii80** [TalAter/annyang#322]
Hello, First of great script! Love it!

I'm trying to create a simple dialogue but is there a way to recognise 'don't' instead of 'do not'.

It is probably a stupid question so i'm sorry for that but i can't seem to find an answer. 

This is what i do:

'dont you think': function() {answerto('dont you think',1);},

This plays a random mp3 file from a folder after the voice command 'dont you think'.
The problem is i can't ad the apostrophe in 'don't' because of the code. So when i say don't you think it doesn't recognise the request because i typed it like 'dont you think'.

How do i do this with annyang?

Thank you for your help in advance.

**Comment by TalAter** [comment]
Have you tried either escaping the apostrophe, or using double quotes?

````javascript
{
'don\'t': 'escaping',
"don't": "double quotes"
}
````
