### ISSUE TITLE
Usage issues

### ISSUE THREAD

**Issue by studioraygun** [TalAter/annyang#323]
Hi, firstly this is a great piece of software and it's working very well in my React app on localhost on Chrome.

However I'm having a couple of issues.

First issue:
When the application is put onto a "real" server (HTTP, not secure), Chrome blocks access to the microphone and I cannot unblock it. It defaults to "Continue blocking microphone access..." despite me changing this. Is this an issue with annyang or Chrome?

Second issue:
In Safari, Edge and Firefox, the annyang object returns null, so voice recognition isn't even firing. In Chrome the object returns populated (on local and production environments). To reiterate this is a React app, and I am using `import`. It is very odd that this is working for Chrome but not other browsers.

All browsers are latest versions.

**Comment by studioraygun** [comment]
Sort of resolved:
1) Still unsure about this, I need to put it on a secure sever to test
2) These browsers don't support speech recognition API yet!

**Comment by TalAter** [comment]
You are correct about both.

It seems like Google has changed support for Speech Recognition in Chrome to only work in on secure origins (HTTPS). This is consistent with their policy on many of the newer browser APIs.

**Comment by zeeshan4119** [comment]
I am using annyang with HTTPS protocol on public site. On chrome the annyang object is populated but In Safari, Edge and Firefox, the annyang object returns null, so voice recognition isn't even firing. This is problem of API or browsers do not support speec recognition?

**Comment by iiison** [comment]
@TalAter It is null on iOS Chrome as well. Is there a way to fix this?

**Comment by TalAter** [comment]
@iiison Chrome on iOS doesn't support the Speech Recognition standard because Chrome on iOS isn't really Chrome.

I just added a section to [the FAQ](https://github.com/TalAter/annyang/blob/master/docs/FAQ.md#what-about-chrome-on-ios) to make this clearer.
