### ISSUE TITLE
I just tried using annyang in my local server it is working fine when i host it in actual server it is not working can anyone help me

### ISSUE THREAD

**Issue by MARUTHESH** [TalAter/annyang#325]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by MARUTHESH** [comment]
i tried using annyang in my local server it is working fine but it is not working when i host it in actual server

**Comment by TalAter** [comment]
Hi @MARUTHESH 
Please provide a lot more details about your code. Maybe even a link to the actual server. Otherwise it would be impossible to help.

P.S. Note that you would probably need to use HTTP on your server because of recent updates to Chrome

**Comment by alaa069** [comment]
Hello @TalAter I have the same problem
I cannot enable mic, I dont know why.
this is my web site : [http://dev.kawaii.ai/test](http://dev.kawaii.ai/test)

**Comment by TalAter** [comment]
@alaa069 See previous message.
Recent changes to Chrome were made that only let you use Speech Recognition in HTTPS
