### ISSUE TITLE
bulk commands

### ISSUE THREAD

**Issue by torosushi** [TalAter/annyang#332]
Due to total of commands, I would like to add the commands dynamically inside the loop but it is not working.

This is what I have so far:

if(annyang){
	var menuName=[],comFunc={},commands={};
	jQuery('.menu_li').each(function(){ 
		menuName.push(jQuery(this).attr('product_name'));
	});
	for(var v=0; v<menuName.length; ++v){
		var comName=menuName[v]; 
		commands[v]={menuName[v]:comFunc[v]};
		comFunc[v]=function(){
			alert(comName);
		}
	}console.log(commands);
	annyang.addCommands(commands);
	annyang.start();
}

How to get it work? Thank you.

**Comment by TalAter** [comment]
Please try and provide code that isolates the problem and is reproducible.

**Comment by torosushi** [comment]
Hi,

is this ok?




if(annyang){
	var menuName=[],comFunc={},commands={};
	menuName= ["Katsu Don", "Ramen Don", "Tempura Noodle", "Karaage Curry", "Katsu Curry", "Tempura Curry", "Tempura Don", "Kaisendon", "Vege Don", "Salmon Don", "Chicken Don", "Beef Don", "(Set) Chicken", "(Set) Ramen", "(Set) Sashimi", "(Set) Sushi", "(Set) Udon", "Miso", "Rice", "Seaweed"]
	console.log(menuName);
	for(var v=0; v<menuName.length; ++v){
		var comName=menuName[v]; 
		commands[v]={comName:comFunc[v]};
		comFunc[v]=function(){
			alert(comName);
		}
	}console.log(commands);
	annyang.addCommands(commands);
	annyang.start();
}

**Comment by TalAter** [comment]
You are creating a commands array that is different from what annyang expects.

You are creating something like:
```javascript
{"0":{comName: func}}
```

This isn't the structure annyang expects. Please check out the API documentation.

You need something more like:
```
  for (var v = 0; v < menuName.length; ++v) {
    var comName = menuName[v];
    commands[comName] = function() {
      alert('boom');
    };
  }
  annyang.addCommands(commands);
```
