### ISSUE TITLE
what's the size of a single record?

### ISSUE THREAD

**Issue by rubyakerman** [TalAter/annyang#335]
i am tring to understand how much bandwise would i need for start using this app,

what's the size of a standard single voice record (lets say of 15 seconds) that we will get from users?

**Comment by TalAter** [comment]
The audio file isn't transferred to you. It is sent directly to the browser vendor. The browser then has access to the transcript.

I suggest reading up on the Speech Recognition API in the browser.

**Comment by rubyakerman** [comment]
so it does'nt make any use of [Google's speech recognition service](https://cloud.google.com/speech-to-text/) right?

**Comment by TalAter** [comment]
No.
