### ISSUE TITLE
Any way for annyang to work on iPad?

### ISSUE THREAD

**Issue by oshihirii** [TalAter/annyang#336]
Any way for annyang to work on iPad?

Thank you.

**Comment by samreid** [comment]
Have you tried Chrome for iPad?

**Comment by tim-phillips** [comment]
Yes by “all browsers” they mean Chrome

**Comment by The-Linguist** [comment]
I have tried installing Chrome on Ipad and Iphone. It doesn't work.
Somewhere around here I've read that Chrome on iOS is not really Chrome but more like Safari with a Chrome skin.

**Comment by TalAter** [comment]
That's about the gist of it @The-Linguist
