### ISSUE TITLE
how can i introduce text with annyang inside a prompt()?

### ISSUE THREAD

**Issue by ceides9497** [TalAter/annyang#342]
I wish that once the prompt appears, I can introduce text in it.
![image](https://user-images.githubusercontent.com/9311740/40188096-24e7e17a-59c7-11e8-915e-f5c558d79508.png)
just ussing annyang
![image](https://user-images.githubusercontent.com/9311740/40188074-1a2b9c22-59c7-11e8-9372-852b2be475d8.png)
And I want accept or cancel the action.
I don't know how do this or if it is possible... help me.
Please is for my project.

**Comment by TalAter** [comment]
I am not aware of a way to programmatically enter values into a `prompt`. This is outside the scope of annyang. You need to research if it is possible to enter values into a prompt using JavaScript.
