### ISSUE TITLE
Trigger command whenever the recognized phrase contains a keyword

### ISSUE THREAD

**Issue by baptisteArnaud** [TalAter/annyang#345]
I was wondering if there is a way to trigger a command whenever a phrase contains a keyword.

For Instance with this kind of command:
```
const commands = {
        'Watson *question': (question) => {
          console.log(question);
        }
      };
```

But it won't be executed when I say 'I like Watson and chocolate'. 
Is it possible to tell the code to grab everything that's after this particular word whenever the phrase starts with it or not?

**Comment by TalAter** [comment]
You could do it with regular expressions as explained [here](https://github.com/TalAter/annyang/blob/master/docs/README.md#using-regular-expressions-in-commands)
