### ISSUE TITLE
Confirmation Command

### ISSUE THREAD

**Issue by jrsarath** [TalAter/annyang#347]
This is a question : 

How can i configure annyang to listen for a confirm command after a command gets executed..
like : 

USER : CLOSE OBJECT
ANNYANG: Are you sure ?
USER : yes
ANNYANG: executes final action 

version used 2.61
MacOS 12.6 - Desktop

**Comment by TalAter** [comment]
This isn't something built into annyang, you would have to programmatically create it.

I would suggest that once you recognize one command you change the available commands to ones of confirmation.

For example:

````javascript
const commands = {
  'close object': () => {
    annyang.removeCommands();
    annyang.addCommands(verificationCommands);
  }
};

const verificationCommands = {
  'yes': () => {
    annyang.removeCommands();
    annyang.addCommands(commands);    
  }
}

// Add our commands to annyang
annyang.addCommands(commands);

// Start listening.
annyang.start();
````

**Comment by jrsarath** [comment]
And is there any chance of getting hotword working ? 
i saw a issue here referring to some annyang.prefix(); which is not defined yet on the library
