### ISSUE TITLE
Way to analyse Microphone input along with Annyang

### ISSUE THREAD

**Issue by jrsarath** [TalAter/annyang#356]
Hi there, 

we can analyse microphone's input by web audio api while using browser default recognition.. Ref: https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getByteFrequencyData

well i tried to do the same with annyang but i failed.. any help or suggestions will be appreciated

**Comment by The-Linguist** [comment]
According to my tests, using the microphone input for a second purpose along with annyang can produce a useful result only on desktop environments and not mobile. It is not just an issue of Android. I have tried it on a Nexus tablet and several phones (all Android). Although none of the devices gave a reliable performance, I remember that one Sony phone was better than the others. Don't know how and why.

**Comment by jrsarath** [comment]
i moved to python from js for my particular use, thanks for your input anyway
