### ISSUE TITLE
Unable to send command with function that has parameters passed

### ISSUE THREAD

**Issue by kobadg** [TalAter/annyang#358]
## Expected Behavior

When creating a command, allow function called to accept parameter, and then fire when triggered.

## Current Behavior

As soon as annyang is started, the trigger is fired. And does not fire again upon being triggered.

## Steps to Reproduce (for bugs)

1. Typical setup, as per documentation with the following for the command/function
```
function triggerFunction(message){
  console.log(message);
}
var command = { 'example': triggerFunction("Send this through!") }
```
2. Init the setup
3. Function defined triggers immediately, and does not trigger again.

## Context

I am making a bot that will be triggered based upon sets of commands. They all will fire the same function, but will give different string inputs. Without the ability to pass the parameter, I cannot tell the function what to do.

## Your Environment

* Version used: latest
* Browser Name and version: chrome | latest
* Operating System and version (desktop or mobile): Win10 desktop
* Additional: Using Laravel & VueJS (Annyang is being used inside the vuejs instance)

**Comment by thefyrewire** [comment]
Hey, not sure if you already found a workaround for this, but to reuse the same function with different parameters, you could do:

```js
let command = {
  'example': triggerFunction.bind(null, 'Send this through!'),
  'test': triggerFunction.bind(null, 'This is a message'),
  'instance': triggerFunction.bind(null, 'Here is a reply'),

  'print (*str)': str => {
    if (str) triggerFunction(`Here is what you said: ${str}`)
    else triggerFunction('Nothing was specified')
  }
}

function triggerFunction(message) {
  console.log(message);
}
```

**Comment by TalAter** [comment]
Thanks @thefyrewire 

You can also just pass a function that calls your function with the parameters

````javascript
let command = {
  'hey': () => triggerFunction('just saying hey!'),
  'yo': () => triggerFunction('yo!'),
}
````
