### ISSUE TITLE
Congratulations for your AWESOME script!!!

### ISSUE THREAD

**Issue by inglesuniversal** [TalAter/annyang#359]
Hello:

I am working on two projects, related to voice recognition. I am proudly using your script on both, on the browser and on a mobile phone. However your script has some issues using it on the cell phone, which mainly, has to do with the microphone going on and off.

Would you allow me to use your code, without the voice recognition module?   Just with the part that deals and handles the commands?

I hope I can count on you.

Best regards

Hugo Boarbosa

**Comment by TalAter** [comment]
Thanks for the kind words Hugo.

Yes, there are some known issues with Chrome on mobile phones. These are known to Google, and actually seem to be by design.

Feel free to reuse the code in any way you see fit.

**Comment by inglesuniversal** [comment]
Thanks ... as a matter of fact... I did... but it makes conflict with the second library which also handles voice recognition.... so, since I've been using your code for a while... can you kindly tell me which lines to remove in order just to use the command recognition module? using * on keywords, (parenthesis), and parcial_text: recognition which are part of your code... in other words, for this project I just want to take advantage of the way you handle commands without the speech recognition module that is already included and working for mobile so far.  Thanks again... I am a GREAT fan of your work.

**Comment by TalAter** [comment]
Thanks Hugo.

That's not an easy answer... you can find some of it around https://github.com/TalAter/annyang/blob/master/src/annyang.js#L56 and https://github.com/TalAter/annyang/blob/master/src/annyang.js#L106
