### ISSUE TITLE
Prioritize exact matches over splats

### ISSUE THREAD

**Issue by arjun010** [TalAter/annyang#360]
Is there a way to prioritize exact command pattern matches over splats? For example, given the following commands object:

    let commands = {
            "hello *person":function () {
                console.log("general")
            },
            "hello there":function () {
                console.log("specific")
            }
        };

For the command "hello there", the library currently prints "general" (i.e., matches the first case). Is there a way to make this work so that it matches the second command since it is a complete match?

**Comment by TalAter** [comment]
No. This isn't currently possible.

Do you have a suggestion on how to implement this in annyang without breaking existing functionality?
