### ISSUE TITLE
annyang on localhost?

### ISSUE THREAD

**Issue by digiteo** [TalAter/annyang#363]
It's possible to host annyang-based project on localhost without SSL? I tried to work with Raspberry and whole project will get dynamic ip so i can't just register domain and put SSL on it...

**Comment by TalAter** [comment]
I think it might be possible as long as you access it as `http://localhost` and not an ip or some other domain (e.g., `http://192.168.1.1`).

But it has been a few years since  I last tried it. You should experiment and share your experience with the community here.

Good luck 👍

**Comment by kylebakerio** [comment]
yes, works on localhost.
