### ISSUE TITLE
Support for Arabic Diacritics

### ISSUE THREAD

**Issue by hayatnoor** [TalAter/annyang#364]
The arabic support works great in this library, but is there any support for the diacritics (vowels) of the arabic language? Here's some more info on it:

https://en.wikipedia.org/wiki/Arabic_diacritics

**Comment by TalAter** [comment]
annyang wraps around the speech recognition engine provided by the browser. It doesn't include it's own speech recognition and so we can't really change it, add support for new languages, or language features.

I suggest you try the browser's support forum.

Good luck 👍
