### ISSUE TITLE
Possible Browser Security Issue

### ISSUE THREAD

**Issue by rocketbear27** [TalAter/annyang#369]
## Screenshots
![capture](https://user-images.githubusercontent.com/40366354/45332523-fb56fe80-b525-11e8-987f-e9184d3c701c.PNG)
![capture2](https://user-images.githubusercontent.com/40366354/45332524-fbef9500-b525-11e8-931d-dca56c9b8fbf.PNG)
![capture3](https://user-images.githubusercontent.com/40366354/45332525-fbef9500-b525-11e8-85f3-cfc27121f39a.PNG)
## Expected Behavior
To run `npm run start` properly and open a localhost with content.

## Current Behavior
When I enter the following code in the command line
``` powershell
> npm run start
```
It runs all checks and behavior properly, then it pop-ups the window (localhost) and all 3 browsers I have tried had the same errors. A Security Issue

## Possible Solution
I am not exactly sure

## Steps to Reproduce (for bugs)

1. Run `npm run start`
2. Wait for it to complete the command line process and pop up a localhost window
3. Observe how the browser does not allow me to access the page for security reasons

## Context
It blocks me from viewing the `npm run start` full process.

## Your Environment

* Version used:
* Browser Name and version: [Google Desktop Chrome 69.0.3497.81](), [Firefox Quantum Desktop 62.0](), and [Microsoft Edge 42.17134.1.0]()
* Operating System and version (desktop or mobile): Desktop Windows 10 Home 
* Link to your project: [Here](https://github.com/rocketbear27/annyang)

**Comment by TalAter** [comment]
This is because you are running HTTPS locally without a registered SSL certificate... which is what you're supposed to do.

Once you upload your code to a server that is properly configured to use HTTP you shouldn't get that message.
