### ISSUE TITLE
annyang supports nested voice commands?

### ISSUE THREAD

**Issue by ananth4u** [TalAter/annyang#380]
Hi Team,
is there a way to incorporate nested voice commands using annyang?
Example:
<script>
var commands = {
'alexa':function(){

'*tag': showFlickr,

}

**Comment by TalAter** [comment]
You can do this by adding and removing commands in response to other commands.

Something like:
````javascript
var commands = {
  'alexa': () => {
    annyang.removeCommands();
    annyang.addCommands(otherCommands);
  }
};
````
