### ISSUE TITLE
Get rid of the beep on start and end of speech recognition? 

### ISSUE THREAD

**Issue by skukan159** [TalAter/annyang#382]
## Context
Is there a way to get rid of the annoying beep every time voice recognition starts and ends on mobile and if not, could you add that feature? The beeping "feature" is not there on PC but it is there on mobile.

**Comment by TalAter** [comment]
That is outside of annyang's control. It's the browser that does that when speech recognition is initiated as a security mechanism so the user knows their speech is transcribed.
