### ISSUE TITLE
when i use +tag this add %20 when i use spaces

### ISSUE THREAD

**Issue by yazui** [TalAter/annyang#383]
I am use  **function(tag)** so i have a simple problem.

When i ask: good songs

Result: good%20songs

Can i change automatic action %20 to +?

my code
```
var showFlickr = function(tag) {
  var url = 'http://api.flickr.com/services/rest/?tags='+tag;
  $.getJSON(url);
}
```

**Comment by TalAter** [comment]
This is more of a JavaScript issue, than an annyang issue.

What you are getting are spaces between words (which when encoded as a URL become %20).

Try replacing spaces with `+` before adding it to the url.

Probably something like:
````JavaScript
tag = tag.replace(/\s/g, '+');
var url = 'http://api.flickr.com/services/rest/?tags='+tag;
````

**Comment by yazui** [comment]
Thanks to help!
