### ISSUE TITLE
Multiple splats within the same command

### ISSUE THREAD

**Issue by kevinrue** [TalAter/annyang#384]
Thanks for the amazing library!

## Expected Behavior

I would like to define a command that contains multiple splats, as shown below:
```
        var commands = {
            'color panel *panel by *title': function(panel, title) {
                Shiny.onInputChange("inputPanel", panel);
                Shiny.onInputChange("inputTitle", title);
            }
        };
```

However, that expression doesn't seem to capture anything (while my other commands work fine in the same session). I suppose that the fact that splats are greedy does not allow multiple splats in the same command?

> Use splats to capture multi-word text at the end of your command (greedy).
> Source: https://www.talater.com/annyang/

## Current Behavior

The current behaviour seems to be that nothing is captured. At least, the Shiny `input$inputPanel ` and `input$inputTitle` do not seem to be updated (they would trigger at some messages in my console).

## Possible Solution

Is it at all possible to support multiple splats by command? Or is it already possible and I'm just missing something.

*Actually,* in the meantime, I just realised that I could capture everything after "color panel" as a single splat, and do the splitting and post-processing in R.

## Steps to Reproduce (for bugs)

1. https://github.com/csoneson/iSEE/tree/multisplat
2. Run script
```
library(iSEE)
library(scRNAseq)
data(allen)
class(allen)

# Example data ----

library(scater)
sce <- as(allen, "SingleCellExperiment")
counts(sce) <- assay(sce, "tophat_counts")
sce <- normalize(sce)

sce <- runPCA(sce, ncomponents=4)
sce <- runTSNE(sce)
rowData(sce)$ave_count <- rowMeans(counts(sce))
rowData(sce)$n_cells <- rowSums(counts(sce)>0)

# Minimal initial panels, for best effect ----

initialPanel = DataFrame(Name="Reduced dimension plot 1", Width=4, Height=200)

# launch the app itself ----

app <- iSEE(sce, initialPanels = initialPanel)
if (interactive()) {
    shiny::runApp(app, port = 1234, launch.browser = FALSE)
}
```

## Context

I am using annyang for Shiny apps as demonstrated [here](https://yihui.shinyapps.io/voice/). I've managed to implement simple commands successfully, and I'm trying to head into more advanced commands.

## Your Environment

* Version used: 2.6.0
* Browser Name and version: Chrome Version 70.0.3538.102 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): macOS Mojave Version 10.14.1
* Link to your project: https://github.com/csoneson/iSEE/tree/multisplat

**Comment by TalAter** [comment]
That's not possible with splats because of their greedy nature, as you correctly understood.

The basic string structure with splats, named commands, and optional words is suitable for simpler string matching. For more sophisticated use cases I suggest going with the more [powerful regular expressions](https://github.com/TalAter/annyang/blob/master/docs/README.md#using-regular-expressions-in-commands).

**Comment by kevinrue** [comment]
Sorry for the slow reply, and thanks for yours.

This situation taught me by experience by multiple small commands with simpler string matching are a lot more efficient than single long commands that are near-impossible to pronounce right.

Best wishes and thanks again for the great software!
