### ISSUE TITLE
Mapping Variables to multiple words in the command

### ISSUE THREAD

**Issue by prasadkrn83** [TalAter/annyang#387]
Is it possible to have multiple words in a command mapped to a single variable
## Expected Behavior

If the command is like "pick all *items"
and the input voice command is "pick all text boxes"
is there a way to map items variable to text boxes since it is having more than 1 word

**Comment by TalAter** [comment]
@sethwilsonUS is correct.

Once you have all the variables in your function, you can do what you want with them such as splitting the string (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split).
