### ISSUE TITLE
Can i use this plugin to compare two voices?

### ISSUE THREAD

**Issue by Er-rchydy** [TalAter/annyang#390]
I have an audio file of an American native  English speaker saying for example "Hello" , and the user can record himself saying that work. is there a way to use this plugin to calculate the match ratio between the  two audios ?
Thanks for the great plugin

**Comment by TalAter** [comment]
Hi @Er-rchydy 

No, that isn't possible with annyang. annyang is only used to get a transcript of what the user says based on the speech recognition engine within the browser (which also cannot give you what you ask for).

**Comment by Er-rchydy** [comment]
Ok thanks, do you have any idea what i need to search for to get what i'm looking for?

**Comment by TalAter** [comment]
Not really,  I'm sorry.
Good luck 👍
