### ISSUE TITLE
Electron Annyang repeatedly Stopping and Starting

### ISSUE THREAD

**Issue by Fenish** [TalAter/annyang#392]
I'am developing a desktop asistant.
And im using annyang for speech recognition.

Sorry im opening new issue becaue i didn't understand other issues.

**Error is that** 

![resim](https://user-images.githubusercontent.com/46840264/54473352-c040cb00-47e7-11e9-8694-0039f0af5aa9.png)

**Code**

```
if (annyang) {
    // Let's define a command.
    var commands = {
      'show': function() { console.log("Welcome"); }
    };
    annyang.debug(true);
    // Add our commands to annyang
    annyang.addCommands(commands);
   
  
    // Start listening.
    annyang.start({ autoRestart: true, continuous: false });
    
  }

```

**Comment by TalAter** [comment]
Cannot reproduce from your description. Please open a bug with a full description based on the issue template.
