### ISSUE TITLE
accent neutralization

### ISSUE THREAD

**Issue by prasadkrn83** [TalAter/annyang#394]
Is there a way to enable accent neutralization of the received voice before it is matched to a command?
Suppose if i have a command "Pick number" due to my accent the tool is recognizing it as "click number" and the command is not getting triggered.

**Comment by TalAter** [comment]
`annyang` has no control over the speech recognition and so cannot enable that feature.

What I can suggest is adding additional command triggers for common misstakes.
e.g.,
````javascript
const pickNumber = () => {console.log('Pick a number')}

const commands = {
  'pick number': pickNumber,
  'click number': pickNumber,
};
````
