### ISSUE TITLE
Regex not taken into account

### ISSUE THREAD

**Issue by nerkdesign** [TalAter/annyang#395]
## Expected Behavior
Hi everyone, 

I wanted to simplify my commands on Annyang using regex but I have some issues. on my first version I wrote every commands (sorry it's in French but it doesn't matter is this issue):

'jarvis news de France': newsapijson,
'jarvis nouvelles de France': newsapijson,
'jarvis actualité de France': newsapijson,
'jarvis *search': searchapi

=> It worked fine

But when I simplify using regex :

'jarvis news de France': {'regexp': /^(?:news|nouvelles|actualité) (\w*)$/, 'callback': newsapijson},
'jarvis *search': searchapi

It doesn't match with regex commands. I tried without accent but it still not working.

Did I miss something ?

## Your Environment
* Version used: annyang.min.js version 2.6.1
* Browser Name and version: Chrome and Chrome Android
* Operating System and version (desktop or mobile): Windows 10 / Android

**Comment by TalAter** [comment]
The problem seems to be that the regex you created doesn't capture the sentences you say. That has nothing to do with annyang.

Try running `/^(?:news|nouvelles|actualité) (\w*)$/.test('jarvis news de France')` in your console and you'll see that it returns false (no match).

Try this instead:
````javascript
/^jarvis (?:news|nouvelles|actualité) ([\w\s]*)$/.exec('jarvis nouvelles de France')
````
