### ISSUE TITLE
The command will be invalid when opening the page with iframe.

### ISSUE THREAD

**Issue by 763790880** [TalAter/annyang#396]
![1556608119(1)](https://user-images.githubusercontent.com/49143352/56945495-fa78e880-6b59-11e9-8983-97e4c429e7c1.jpg)
![image](https://user-images.githubusercontent.com/49143352/56945576-3318c200-6b5a-11e9-8678-d981d6dcebe6.png)
(Google Translate) When both pages are defined and listened to, all commands will be invalidated. How can I make Annyang listen to all commands?

**Comment by 763790880** [comment]
![image](https://user-images.githubusercontent.com/49143352/56946686-64df5800-6b5d-11e9-8470-2ed0957f4ed1.png)

**Comment by TalAter** [comment]
You cannot have more than one tab / page / iframe listening at the same time in Chrome.

If you start listening on page B while page A is already listening, page A will stop listening.

That's a limitation set by the browser.
