### ISSUE TITLE
Auto-restart won't work on tablet while on desktop and on phone it just works.

### ISSUE THREAD

**Issue by The-Linguist** [TalAter/annyang#398]
After double reexamining and triple checking it looks like this happens when there is another piece of code that wants to read the microphone input along with annyang.
In my case I'm using the wavesurfer.js library with the microphone plugin which produces some nice waveform visuals as it reacts to the audio level of the users voice.
There is no problem on my desktop and there is no problem on my Sony Experia phone with this. But with my ASUS Nexus 7 tablet (Chrome 74 / Android 6.0.1) this situation of shared-microphone-input causes a problem. It just terminates all listening sessions as soon as they are started.
## Expected Behavior

I'm planning to use annyang in my educational web application and I naturally want it to work on as many platforms as possible.

It would be really nice if somehow my tablet device could do what the phone is able to do.

As this is a "TABLET ONLY" problem I guess any possible code solution would have to be a "TABLET ONLY" solution.

Thanks in advance to all that read this.

**Comment by TalAter** [comment]
Thanks for reporting the issue @The-Linguist 

Unfortunately I don't have a tablet to test this on. If you are willing to try and troubleshoot and isolate the problem, and maybe even offer a solution everyone can benefit from, that would be great 👍

Thank you.

**Comment by The-Linguist** [comment]
OK. Here are some interesting details.
It looks like the problem has to do something with the "microphone activation/deactivation".
First thing to note is that I've realized that manual restarting on core Web Speech API was also unstable on my tablet while it runs perfectly on the desktop PC and on the phone.
As an example, if I visit https://mdn.github.io/web-speech-api/speech-color-changer/ on my tablet, the first listening session is fired with a touch event on the page and it works just fine like it does on other environments.
But after a few successful sessions if there is a session without any speech input (like a long silence from the user after the starting DING tone) it SOMETIMES (in an unpredictable way) ends with an **_error tone_** and causes GoogleChrome-AsusTablet couple to stop reacting to the user at all and the page goes LOCKED. 

Something similar happens when I visit https://www.talater.com/annyang/  on the tablet. By silently watching the microphone icon and listening to the DING tones I can tell that the autoRestart actually works on the tablet too but that is only a few times (usually 5  or 6) before the page interaction gets locked (or should I say before the speech recognition is dead) unless I keep speaking to feed it some voice input so that it wouldn't end with that error tone.

And here is something maybe like a first step towards a possible solution.
As I said there are no problems on the phone, so I compared the tablet behavior with the phone behavior (same OS, same browser). The "obvious" difference is that the phone keeps listening to my silence forever as it successfully refreshes the speech recognition session every four ~ six seconds while DINGing at the beginning of each session whereas the tablet completely STOPS reacting after just a few session-restarts.

The "not so obvious" difference is that the time interval between two consecutive listening sessions is shorter on the tablet than it is on the phone (perhaps a few hundred milliseconds or so). 
And what I have discovered is that once the tablet's speech recognition gets locked as described above it can actually be unlocked by resetting the microphone. A microphone reset on the tablet (in my case) can be achieved by either 

1. refreshing the page or
2. viewing a different browser tab and then coming back or 
3. switching to a different app and then coming back to chrome

Both tablet and phone: Not receiving speech input during a listening session SOMETIMES ends with an error tone while other times it ends without any tone or any dinging. The phone however is able to restart in both cases. But the tablet can only restart if there ISN'T an ERROR TONE. If there is an error tone the tablet goes into a state of "not responding" while the microphone icon stays "on". To make it respond again the microphone has to be deactivated and reactivated.

There is one more thing that produces this error tone and it is the microphone being already activated by something else when `annyang.start()` is executed. In my case I'm intending to combine the great annyang with this cool JS library called wavesurfer https://wavesurfer-js.org/plugins/microphone.html which also needs to access the microphone.
In my code `wavesurfer.microphone.start();` is called long before `annyang.start();` is called . In this case both the tablet and the phone DING like the very first annyang listening session fails immediately with an error tone. The difference is that the phone is able to restart the next listening session which works fine. But the speech recognition on the tablet just gets locked.
Although this goes somewhat beyond the topic I would like to be able to avoid this second error as the immediate termination of the first listening session produces misleading DING tones for the user even if the phone is able to keep listening during the second and the following sessions.

Any help is appreciated.

**Comment by The-Linguist** [comment]
So I think the question is "**Is there a way to reset the microphone (turn it off and then on again) everytime annyang auto-restarts?**" (I'm assuming that the current version of annyang is not doing such a thing, am I wrong?)
If the answer is yes and if it solves this problem by making my Asus Nexus7 tablet (and any other device that has this issue) behave exactly like my Sony Experia phone (i.e. make it listen to my silence forever therefore stay ready to accept speech input forever) then can it be added to annyang as maybe something like
`annyang.start({ forcedAutoRestart: true });`
