### ISSUE TITLE
How to make mobile browsers continue listening when the user views a different browser tab and then comes back

### ISSUE THREAD

**Issue by The-Linguist** [TalAter/annyang#399]
I've found that on Chrome for mobile, if the ON/OFF button of the device is pressed or if the user changes tabs to browse another page and then returns to the tab where annyang is supposed to be listening, it won't be listening anymore. To make it listen you then have to refresh the page (which is something that you wouldn’t want to do in the middle of your progress through a web application).

The simplest workaround to make it listen WITHOUT a page refresh (i.e. a document reload) is below, (EDIT: THIS ONLY WORKS FOR TABLET on certain conditions and may not be good enough for phone. I will explain why.)
```
document.addEventListener("visibilitychange", function() {
    if (document.hidden){
        annyang.abort();
        console.log("This browser tab is now hidden");
    } else {
        annyang.start();
        console.log("This browser tab is visible again");
    }
});
```
EDIT: Chrome does not let you see the console window on mobile devices. Yet the difference between the phone and the tablet became obvious to me only after using https://github.com/liriliri/eruda
You can try it easily by adding these two lines into your document (check for updates at will), 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/eruda/1.5.8/eruda.min.js"></script>
<script>eruda.init();</script>
```
It will be easier to see if you have this in your document: `<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">`
A gear icon appears on your page and “tadaa” you have a console window on mobile.

**Comment by The-Linguist** [comment]
Let me explain the difference between tablets and phones. On a tablet when you want to change the browser tab there is only ONE step. You just tap where you want to go and you are there.
![tablet_tabs](https://user-images.githubusercontent.com/50925914/65818257-947fb280-e218-11e9-80d8-fdd44e3d70fc.jpg)

On a phone however that process is made of TWO steps. Let's say you start like this,
![Change-Tab_phone](https://user-images.githubusercontent.com/50925914/65818290-e9bbc400-e218-11e9-8373-277c10888e2e.png)

To go to another tab you first tap the TABS icon and this brings you to a fly-over menu like this,
![github_phone_tabs](https://user-images.githubusercontent.com/50925914/65818260-a4979200-e218-11e9-91ef-274a09066749.jpg)

And that is the critical point. Because now the question is, "When a user is at this intermediate stage should he be considered AWAY or not?"

In ECMAscript (=javascript) you can try to find this either by using the "visibilitychange" event on the document or by using the window-blur/window-focus couple. According to visibilitychange, the user is not yet away from the document at this stage. But according to window blur/focus the user is away.

Here is my final code,
```
var nowIsTheTimeForAnnyang = false;
annyang.start({ autoRestart: true });
nowIsTheTimeForAnnyang = true; // This can be used elsewhere in code to control the turning on/off

window.addEventListener('blur', blurHappenedF);
function blurHappenedF()
      {
        if(nowIsTheTimeForAnnyang){
          annyang.start({ autoRestart: false }); // This might be necessary before going off.
          annyang.abort();
          console.log("turn off annyang");
        }
        console.log("Blur! That means the user is away");
      }

window.addEventListener('focus', focusHappenedF);
function focusHappenedF()
      {
        if(nowIsTheTimeForAnnyang)
        { 
          setTimeout(function(){ annyang.start({ autoRestart: true }); }, 1000); // a little delay feels better
          console.log("turn on annyang");
        }
        console.log("Focus! That means the user is here");
      }
```

**Comment by TalAter** [comment]
Thanks @The-Linguist 
That might be useful to some people, though I don't think it should be a native feature of annyang.

My guess would be that in order to save on battery life the JavaScript code isn't executed when the tab isn't visible.

P.S., for debugging on your mobile I highly recommend using something like [remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging). Once you get it set up, it feels like magic ⚡️
