### ISSUE TITLE
How to stop manually?

### ISSUE THREAD

**Issue by deadmann** [TalAter/annyang#402]
how to stop hearing manually?

i need something like beginHear() and endHear(),... or i need to start->onEnd{restart} -> onEnd{restart} -> end {don't record things are said after user pressed stop.}

**Comment by TalAter** [comment]
You can either stop the microphone from listening completely using `annyang.abort()` and then restart it with `annyang.start()`, or you can simply pause annyang from responding to commands using `annyang.pause()` and then `annyang.resume()`. The latter will make annyang not act on the commands, but speech recognition will still run in the background... it does have the benefit of not having to restart the speech recognition engine (and possibly asking for permission a second time).

* [abort](https://github.com/TalAter/annyang/tree/master/docs#abort)
* [start](https://github.com/TalAter/annyang/tree/master/docs#startoptions)
* [pause](https://github.com/TalAter/annyang/tree/master/docs#pause)
* [resume](https://github.com/TalAter/annyang/tree/master/docs#resume)
