### ISSUE TITLE
"Hello world" demo can not work

### ISSUE THREAD

**Issue by liugyer** [TalAter/annyang#407]
## Expected Behavior

It should detect my word "hello" and emit an alert.
## Current Behavior

There was only a hint to turn on the mic, but my voice was not recognized.
## Steps to Reproduce (for bugs)

The source code as following:

```html
<html>
<body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/annyang/2.6.0/annyang.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/SpeechKITT/1.0.0/speechkitt.min.js"></script>
<script>
console.log("annyang");
if (annyang) {
  console.log("add our commands");
  // Add our commands to annyang
  annyang.addCommands({
    'Hello': function() { alert('Hello world!'); }
  });

  // Tell KITT to use annyang
  SpeechKITT.annyang();

  // Define a stylesheet for KITT to use
  SpeechKITT.setStylesheet('https://cdnjs.cloudflare.com/ajax/libs/SpeechKITT/1.0.0/themes/flat.css');

  // Render KITT's interface
  SpeechKITT.vroom();
}
</script>

</body>
</html>
```

## Your Environment

* Version used:
* Browser name and version:
* Operating system and version (desktop or mobile):
* Link to your project:

**Comment by liugyer** [comment]
By the way, when I add the "annyang.debug();", I can find the log: "Command successfully loaded: Hello".
My Chrom version :  78.0.3904.70（64 bits）

**Comment by TalAter** [comment]
I just tried your code and it works.

![SpeechKITT](https://user-images.githubusercontent.com/926653/67897137-71715700-fb66-11e9-8037-179bf3e2cce3.gif)

I am on Chrome Version 77.0.3865.120 (Official Build) (64-bit)

Did you click SpeechKITT's microphone button?

**Comment by TalAter** [comment]
Also tested in `Version 78.0.3904.70 (Official Build) (64-bit)` and it works. Both tests were on macOS
