### ISSUE TITLE
Using annyang for Commercial use. 

### ISSUE THREAD

**Issue by khoantv** [TalAter/annyang#412]
I want to use annyang in my website. As I know, this library is free for commercial use. But, I don't know whether I pay any money for anything or not? (like Google cloud speech server or anything).
Million Thanks.

**Comment by TalAter** [comment]
annyang's code is licensed as MIT and provided as-is.

I cannot guarantee costs for other things, but as of the time of writing using the browser's speech API in Chrome is free.

**Comment by khoantv** [comment]
> annyang's code is licensed as MIT and provided as-is.
> 
> I cannot guarantee costs for other things, but as of the time of writing using the browser's speech API in Chrome is free.

Thanks u so much.
