### ISSUE TITLE
"This " keyword issue.

### ISSUE THREAD

**Issue by rnkpareek** [TalAter/annyang#424]
I want to fill my form using this ,But when iam setting the command and function.
The function is being called bu unable to read the "this" keyword and gives error.

Uncaught TypeError: Cannot read property 'registerForm' of undefined
    at onSubmit (app.component.ts:111)
    at P (annyang.min.js:12)
    at SpeechRecognition.a.onresult (annyang.min.js:12)

**Comment by TalAter** [comment]
This is most likely not an _annyang_ specific issue but simply the way JavaScript functions behave.
You are passing a function and then having it called from a different context so the `this` is different.

I would suggest looking at something like [`bind()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind)

> The bind() method creates a new function that, when called, has its this keyword set to the provided value, with a given sequence of arguments preceding any provided when the new function is called.
