### ISSUE TITLE
Getting misrecognition friendly and lisp friendly

### ISSUE THREAD

**Issue by The-Linguist** [TalAter/annyang#425]
In most cases the success rate and the accuracy of speech recognition is just amazing. However there are times like when "I scream" can be recognized as "ice cream" or vice versa. Or like "real eyes" and "realize" and "real lies" etc. Another thing is that the user could have a lisp and could only say "three" when he tries to say "tree". Therefore, in order to let the user have a "perfect experience", it is essential to forgive mispronunciations and work around misrecognitions. The more tests I do, the more obligation I feel towards including possible mistakes/mismatches in the code. For example,

        var commands =    {
          'tree': functionOfWhatToDoWhenUserSaysTree,
          'three': functionOfWhatToDoWhenUserSaysTree,
          'free': functionOfWhatToDoWhenUserSaysTree
          // ... this list could get long for certain words and phrases! Especially in non-english situations.
        };
        annyang.addCommands(commands);

What I would like to be able to do is, shorten that code so that one single string would contain all such possibilities. And thus everything would fit in one single line.
The code would then look something like,
`var commands =    {   'tree OR three OR free': functionOfWhatToDoWhenUserSaysTree   };`
or more simply
`var commands =    {   'tree, three, free': functionOfWhatToDoWhenUserSaysTree   };`
or anything instead of using commas or turning capital 'OR' into a keyword.

That would be nice and useful for everyone, wouldn't it?
Sorry if that is already possible and I just didn't know. This issue may be closed if there already has been a way to do it.

**Comment by TalAter** [comment]
Hey @The-Linguist 

The basic syntax for defining commands is relatively simple and doesn't support that. But there is a solution.

You can define alternative transcriptions (and much more) by using [regular expressions to define your commands](https://github.com/TalAter/annyang/blob/master/docs/README.md#using-regular-expressions-in-commands).

For example:
```js
const commands = {
  'favorite tree': {'regexp': /^What is your favorite (tree|three|free)$/, 'callback': functionOfWhatToDoWhenUserSaysTree}
}
```

**Comment by The-Linguist** [comment]
Thank you @TalAter . Your support is awesome.
One last thing: The architecture of my particular web-application is designed to be expandable. In order to make things work, I had to remove all of the actual commands from the `.js` files and had to put them in separate `.txt` files which makes everything not only nice and tidy but also workable with non-coder people. Also because it is so neat to use the `fetch()` method to get the commands from `.txt` files conditionally.
What I can do for example is, after using `fetch()` to get the string `go|dough|no|oh|bow` from `go.txt` file, I obviously can have a string variable like,
`       let goAndPossibleMishaps = "go|dough|no|oh|bow";       `
Then the question that reveals my lack of expertise in EcmaScript is,

- Is it possible to create such an advanced command object by using `goAndPossibleMishaps`? Perhaps ending with something like `'callback': functionOfWhatToDoWhenUserSaysGo`

**Comment by TalAter** [comment]
By the way, the browser's speech recognition engine doesn't return only a single result for what it thinks you said. It will return a few and annyang [matches the top 5 possible phrases](https://github.com/TalAter/annyang/blob/317bc640d171c3ba7d45b0c2a79d6dcf7828a490/src/annyang.js#L124) against your commands. So some of those alternatives might be caught automatically without you having to write all the alternatives.

![CleanShot 2020-08-01 at 14 20 08@2x](https://user-images.githubusercontent.com/926653/89100733-25f41e00-d402-11ea-8220-56183518a98c.jpg)

**Comment by The-Linguist** [comment]
That's great . Definitely makes our apps MUCH more usable. Nevertheless, my tests show that the programmer's intervention can still be necessary to bring things closer to perfect. That is, especially when the browser is listening to human speech that is not in English. In Japanese, for instance, there are 10 different possible Kanji characters that are all pronounced "Ki" and another 10 for just "Hi".
Your kindness and “being concerned” is appreciated.
Regards!
