### ISSUE TITLE
Does it accept an Audio File and convert to text ?

### ISSUE THREAD

**Issue by Unmesh28** [TalAter/annyang#429]
Great stuff.. 
I am just curious to know if it supports "Speech to text from an audio file" ?? If yes , How can we achieve that ?

**Comment by TalAter** [comment]
Hi @Unmesh28 
No. annyang does not do that.

**Comment by Unmesh28** [comment]
> Hi @Unmesh28
> No. annyang does not do that.

Okay, thanks
