### ISSUE TITLE
is it possible to use this with node-webkit?

### ISSUE THREAD

**Issue by isimmons** [TalAter/annyang#44]
I'm just learning node-webkit and also just found this library today. It works great in the chrome browser, and I am able to get a audio stream in my hello world node-webkit application via the webkitGetUserMedia plugin. But annyang doesn't seem to be working. No errors, just not doing anything.

By the way, just testing with a simple command:

```
 var commands = {
        'go away': function() {
          window.close();
        }
      };

      annyang.init(commands);
      annyang.start();
```

**Comment by JaredCubilla** [comment]
+1
