### ISSUE TITLE
Pass additionals parameters to callback

### ISSUE THREAD

**Issue by zoic21** [TalAter/annyang#56]
Hi,

Are they any solution to pass additionnal parameters to callback (not speak parameters) ? Somethink like this : 

var commands = {
    'additional parameters': (function(myParam) {
      alert(myParam);
    })('plop')
  };

**Comment by pieroit** [comment]
I have a difficulty passing parameters to the events callbacks. For example:

<pre><code>
// callback to register command history
annyang.addCallback('resultMatch', function( e ) {
     console.log( e );
});
</code></pre>

'e' is undefined. How do I access from the callback what command (and parameters) where issued?

Thanks :)

**Comment by pieroit** [comment]
bump
