### ISSUE TITLE
prevent repeated confirmation of microphone usage in chrome

### ISSUE THREAD

**Issue by ddsky** [TalAter/annyang#66]
Chrome keeps asking me whether I would allow or deny the page to use the microphone. Even after hundreds of clicks on Allow, it keeps asking me and the functionality of annyang does not work.

Any ideas why that is?

**Comment by karm4ma** [comment]
I faced the same issue with my website. Any ideas to overcome the same?

**Comment by artforlife** [comment]
I am also having this same issue. What is interesting, my local environment works well; however, when I push it to production (AWS EC2 instance), the site repeatedly asks me to allow or block the usage of microphone every 5-10 seconds. Does anyone know why this happens?

**Comment by calebeaires** [comment]
@artforlife I have the same issue, have you every got it done?

**Comment by XiaoxiaoLi** [comment]
Same issue as @artforlife

**Comment by itsshreyarora** [comment]
in the javascript, use `recognition.continuous = true;' to make the setting stick. 
Be default, Chrome will only return a single result.
By enabling "continuous", Chrome will keep the microphone active.

**Comment by itsshreyarora** [comment]
> I am also having this same issue. What is interesting, my local environment works well; however, when I push it to production (AWS EC2 instance), the site repeatedly asks me to allow or block the usage of microphone every 5-10 seconds. Does anyone know why this happens?


in the javascript, use `recognition.continuous = true;' to make the setting stick.
Be default, Chrome will only return a single result.
By enabling "continuous", Chrome will keep the microphone active.
