### ISSUE TITLE
Not giving credit to Google or Microsoft for their speech recognition engines/services

### ISSUE THREAD

**Issue by runvnc** [TalAter/annyang#69]
You have done a great job of making the HTML 5 SpeechRecognition API easier to use across browsers.  However, the way you describe your library as having no dependencies makes it sound as though you literally invented a way to do speech recognition in 2kb of JavaScript.  Quite a few people are going to see that and think hey if that guy can do it, why can't my programmer implement speech recognition from scratch in a weekend?  The majority of the speech recognition being done is happening on Googles speech recognition servers which are state of the art and rely on very large databases and resources.

**Comment by nmstoker** [comment]
I think Annyang is excellent, but I do agree it would simply be helpful to include slightly more detail on what's actually going on (ie it's using the underlying speech recogniser facilities of the browser).

This would be useful for two reasons:
i. Giving credit
ii. Reassuring users about who actually accesses their speech data (I was looking to see if Annyang was somehow doing the recognition with it's own service and it was only clear when I dug into the code).

For point ii, no offence is meant, it's a matter of wanting to know so an informed decision can be made.

Adding to the README would be the best place for this. Barring that, simply including an FAQ on https://www.talater.com/annyang/ would be reasonable (if there's something in the comments section then that doesn't really cut it IMHO)

**Comment by LukeMcLachlan** [comment]
I think a credit is important and @nmstoker makes a very good point about privacy, but a credit along the lines of "and a thank you to Google who has invested millions if not billions in the technology that makes Annyang possible" is overkill; Google/Alphabet makes billions and understands that they have a responsibility to give back. Simply mentioning their name, how Annyang utilises their technology and how speech data is utilised by them is sufficient in my eyes.
