### ISSUE TITLE
Annyang and Mobile Chrome Apps

### ISSUE THREAD

**Issue by luiseduardobrito** [TalAter/annyang#74]
Any chance of get it working using the Chrome WebView from CCA?

https://github.com/MobileChromeApps/mobile-chrome-apps

**Comment by TalAter** [comment]
It looks like that plugin handles all of the functionality on its own, so annyang won't work with it out of the box.

You might be able to hack something if you combine [Corti](https://github.com/TalAter/Corti) with annyang and pass the results from that plugin to Corti using its `say` command.

It seems to me like too much work for the payoff you are getting though.
