### ISSUE TITLE
Any solution to add "loading" ability (by identifying whether the recognition has been performed)?

### ISSUE THREAD

**Issue by unmeshpro** [TalAter/annyang#81]
@TalAter  I am using annyang.js with a three.js application and it seems quite disturbing not to know whether the speech is being recognized. Is there a way to monitor the state of request to recognize and the response from annyang so that I may add a loading or waiting animation?

**Comment by lmangani** [comment]
https://github.com/TalAter/annyang/issues/97

**Comment by alanjames1987** [comment]
I've also requested a feature like this in #101.

**Comment by TalAter** [comment]
@unmeshpro - is this similar to #47 ?

**Comment by TalAter** [comment]
I would like to include such functionalities as plugins which would extend annyang's functionality, while keeping the base library lean.
@unmeshpro , @lmangani , @alanjames1987 - I would love your feedback on this at #60

**Comment by unmeshpro** [comment]
Yes.. @TalAter .. That's similar to #47 ..

**Comment by TalAter** [comment]
It is currently impossible to do this because of what I believe is a bug in Chrome. I have opened a [bug report](https://code.google.com/p/chromium/issues/detail?id=572697) with the Chromium team, and am awaiting their response.
