### ISSUE TITLE
Unit Testing Annyang

### ISSUE THREAD

**Issue by alanjames1987** [TalAter/annyang#91]
How would one go about unit testing Annyang. I know I can use QUnit or any other unit testing library to run the code, but how do I send sound to it?

I know this is really an issue with the webkitspeechrecognition object, but this seems like a good place to ask.

**Comment by delaman** [comment]
I am also interested in this task.  

Any progress from anyone on this?

**Comment by sktguha** [comment]
I think sinon.js is great for creating mockups of inbuilt objects. 
"Test spies, stubs and mocks for JavaScript"
http://sinonjs.org/
https://github.com/cjohansen/Sinon.JS

**Comment by TalAter** [comment]
Update: I have begun creating a small mock object which can be used for testing SpeechRecognition, and open sourced it under the name [Corti](https://github.com/TalAter/corti).

This is already in use for testing [SpeechKITT](https://github.com/TalAter/SpeechKITT).

I will set up the structure around testing annyang soon. Hopefully the community would be interested in helping write tests.

**Comment by sktguha** [comment]
awesome :+1:

**Comment by TalAter** [comment]
:star: Great news, I've just pushed a number of commits that finally add unit testing to annyang.

The new setup uses [Jasmine](http://jasmine.github.io/) for testing, [Corti](https://github.com/TalAter/Corti) to mock the SpeechRecognition object in a testing environment and [Istanbul](https://github.com/gotwarlost/istanbul) for code coverage.

The test suite runs when you run the default grunt task (or the test task specifically)

![testing annyang](http://i.imgur.com/Jx3j4bk.gif)

The framework for testing is there, but the test coverage is still very poor.

If you have some time, I would love your help in writing more tests :heart:
