### ISSUE TITLE
Safari?

### ISSUE THREAD

**Issue by poshetz** [TalAter/annyang#95]
Hi, does this awesome project will work on Safari and more specifically Safari iOS ?

If it does not, is there any way to make it to work with the cordova or phonegap media audio capture plugin? https://github.com/apache/cordova-plugin-media-capture/blob/master/doc/index.md 

thank you

**Comment by alanjames1987** [comment]
Annyang works by using the `webkitSpeechRecognition` object which is currently only available in Chrome. 

Android has built in speech recognition but it does not allow for continuous speech recognition like Annyang does.

If you want an easy to use speech recognition for Android I recommend this one. 
https://github.com/poiuytrez/SpeechRecognizer

**Comment by TalAter** [comment]
@poshetz  - Safari hasn't adopted the SpeechRecognition standard yet.
Thanks @alanjames1987  :thumbsup:
