### ISSUE TITLE
How can I get the sentence i said?

### ISSUE THREAD

**Issue by youkochan** [TalAter/annyang#97]
I want to show the result...  :)

**Comment by getflourish** [comment]
+1

**Comment by lmangani** [comment]
```annyang.debug();``` will display the results (and much more) in your console

If you need to do something with the result you can play with custom commands.
An abstract example:

```
...

if (annyang) {
   annyang.start();
   var sayThis = function(result) {   $("#output").text(result); console.log(result); }
   var commands = { '*say': sayThis  };
   annyang.addCommands(commands);
}

...
```

**Comment by youkochan** [comment]
@lmangani 
Thank you very much

**Comment by TalAter** [comment]
Starting with [annyang v2.0.0](https://github.com/TalAter/annyang/releases/tag/v2.0.0), the `result`, `resultNoMatch` & `resultMatch` callbacks are now called with a list of phrases the user said.

So you can do something like:
````javascript
annyang.addCallback('result', function(phrases) {
  console.log('Speech recognized. Possible sentences said:');
  console.log(phrases);
});
````

**Comment by DONGILBAE** [comment]
Thank you so much. i was finding this function whole night. thanks again.

**Comment by popbijoux** [comment]
I wrote a detailed question just now, how can I get what the user said (everything they said, both matching commands and not matching) and output it onto a div, the way traditional text dictation works? I can do this with the javascript web api on chrome but can't figure out if this is something I can do with annyang...
